### ISSUE TITLE
Playback of network streams fails on RPi2 with multiple profiles

### ISSUE THREAD

**Issue by DimmiDonger** [OpenELEC/OpenELEC.tv#4115] opened 2015-04-29 22:06 UTC
Hello,

following error occurs on RPi2 with OpenELEC 5.0.8 and current development version (I used 160dc2d83a029465c7761334aa62cff52b18678e from git with kodi-15.0-beta1-7dacc6e):
1: log in with master profile
2: start playback from Youtube addon or sftp mount. It works.
3: stop playback 
4: switch to other profile
5: try to start playback from Youtube or from sftp mount. It does not work. Error message is:

> 23:45:53 T:1747993664  NOTICE: Thread DVDPlayer start, auto delete: false
> 23:45:53 T:1747993664  NOTICE: Creating InputStream
> 23:45:53 T:1747993664   DEBUG: CFileCache::Open - opening <...> using cache
> 23:45:53 T:1747993664   ERROR: Open - Unhandled exception
> 23:45:53 T:1747993664   ERROR: Open - Error opening sftp://USERNAME:PASSWORD@192.168.1.5:22/...
> 23:45:53 T:1747993664   ERROR: CDVDPlayer::OpenInputStream - error opening sftp://...:...@192.168.1.5:22/....mp4
> 23:45:53 T:1747993664  NOTICE: CDVDPlayer::OnExit()

6: switch back to master profile
7: try to start playback from Youtube or sftp mount. It does not work. Same error message as previous is rising. From now on the only possibility to start playback from network is to reboot.

This behaviour is observed and reported by several OpenELEC users on Rpi2, see following threads: http://forum.kodi.tv/showthread.php?tid=223213 and http://forum.kodi.tv/showthread.php?tid=224564. It seems, that this error is specific for OpenELEC in combination with Rpi2. This is the reason why I report this issue here and not to Kodi team.

I was able to trace where the exception occurs using additional debug statements: when a playback is started, CDVDPlayer::OpenInputStream() is called. CDVDPlayer::OpenInputStream(...) calls CFile::Open(...). CFile::Open(...) calls in turn CFileCache::Open(...). CFileCache::Open(...) makes call to ???::Get() ("m_sourcePath = url.Get();", see line 187 from FileCache.cpp). The last call generates some kind of exception, that is logged with "ERROR: Open - Unhandled exception" from line 318 of File.cpp.

Regards

**Comment by stefansaraev** [comment] 2015-04-30 07:39
on rpi/2. with sqlite. nothing works when not using master profile. it's caused by the big rpi backport patchset. 

ping @sraue 

//cc @popcornmix

**Comment by popcornmix** [comment] 2015-05-01 11:10
I can't imagine anything in the pi specific patchset that could explain this.
But I'll see if I can reproduce.

**Comment by daxxi13** [comment] 2015-05-02 13:45
II was the one who reported this issue on chat. I confirm, it works without this patch.
I tried to compile with this patch and commenting some for find which one is buggy.
For now it works without patches numbers : 26, 28, 34, 38, 40, 45, 49, 58 on this file.

The simplier way i found to reproduce this issue is to install an addon on other profile than master.

**Comment by MilhouseVH** [comment] 2015-05-02 13:49
What patch?

**Comment by daxxi13** [comment] 2015-05-02 15:12
this one :
projects/RPi2/patches/kodi/kodi-001-helix_rpb_backports.patch

**Comment by MilhouseVH** [comment] 2015-05-02 15:56
> For now it works without patches numbers : 26, 28, 34, 38, 40, 45, 49, 58 on this file.

Hard to see what effect most of those patches will have on profiles - presumably it's not all of them that you are saying need to be dropped, just that those are the ones you tried?

Perhaps database access (patch 58) is becoming confused by a profile switch...

**Comment by daxxi13** [comment] 2015-05-02 16:13
I uncomment one by one and it fails with patch n° 28
I need another test, i'll come back after

**Comment by popcornmix** [comment] 2015-05-02 17:12
Agree that 58 looks like the only possible cause for this issue.
@daxxi13 Can you test with just "[PATCH 58/75] [PVR] Fix for slow metadata updates of recordings" reverted?

**Comment by daxxi13** [comment] 2015-05-02 17:42
when i comment only patch 26 and 28
i have this question  http://pastebin.com/rZiEhx5u
I say yes and it works fine

**Comment by MilhouseVH** [comment] 2015-05-02 17:45
Yes, it's 28.

I've just gone back through the really old builds and the bug first appears in [#0711](http://forum.kodi.tv/showthread.php?tid=192380&pid=1751177#pid1751177) - I must give *huge* thanks to @delinend for continuing to host these files!

The problem commit is in [newclock3](https://github.com/xbmc/xbmc/compare/xbmc:e4e1561...popcornmix:b269506), and it's the [cachemembuffersize](https://github.com/xbmc/xbmc/commit/ff57df49bd193dee38ea463aaeff071a9b5e8b21) change - my guess is that it becomes screwed up on a profile change.

If the following is added to the users advancedsettings.xml, then YouTube videos play before and after a profile switch with build [#0711](http://forum.kodi.tv/showthread.php?tid=192380&pid=1751177#pid1751177):

```
  <network>
    <cachemembuffersize>20971520</cachemembuffersize>
  </network>
```

I'm able to reproduce this YouTube/profile problem in the very latest [Kodi 15 test build](http://forum.kodi.tv/showthread.php?tid=224025), and the above as.xml addition fixes the problem there too, so I'm pretty sure this is the issue, although I don't know what the fix is (profiles, eugh!)

**Comment by daxxi13** [comment] 2015-05-02 17:48
I tried to only comment patch 28 without succes (now i doubt about it :( )
i'll retry  just after the test without patch 58

**Comment by MilhouseVH** [comment] 2015-05-02 17:52
No need to comment it and build anything, just try adding the advancedsettings.xml and see if it has any effect with your current OpenELEC 5.0.8 build - if it does, then we know that it's the default `cachemembuffersize` that is being knackered on a profile switch.

**Comment by popcornmix** [comment] 2015-05-02 17:53
@daxxi13 / @MilhouseVH 
Thanks. That makes sense. I suspect CAdvancedSettings::Initialize must get called on a profile switch which I hadn't considered. We replace the initial "~0" setting here:
https://github.com/xbmc/xbmc/commit/ff57df49bd193dee38ea463aaeff071a9b5e8b21#diff-2c328e92a68434623c3bbb6f7975c7bcR79
but we're not going to fix a subsequent one. That will result in a cachemembuffersize of ~0 which presumably fails to allocate and so fails to play.

As @MilhouseVH says, explicitly setting cachemembuffersize should be a safe workaround until I think of a cleaner way to implement this.

**Comment by daxxi13** [comment] 2015-05-02 18:01
I confirm, I added advancedsettings.xml on a profile and it solve the issue, just needed to logoff-login

**Comment by stefansaraev** [comment] 2015-05-03 12:39
@popcornmix @MilhouseVH unfortunately, this is also broken in our official "stable" builds, too. and somehow got unnoticed for long. I dont know if @sraue has plans to release at least one bugfix stable release or not, if he wants to, a propper fix would be welcome. force changing cachemembuffersize for  stables is meh.

**Comment by popcornmix** [comment] 2015-05-03 12:51
Yes, will fix for master and helix. Away this weekend, but should fix it Tuesday.

**Comment by popcornmix** [comment] 2015-05-08 14:08
This is reported as fixed in recent Milhouse builds, and the fix in on helix_rbp_backports branch.

**Comment by stefansaraev** [comment] 2015-05-08 14:09
thanks @popcornmix 
@sraue could you please pick for 5.0.x ?

**Comment by stefansaraev** [comment] 2015-06-25 15:47
yea, it seems @sraue does not care, but is busy breaking betas. closing.

**Closed by stefansaraev** 2015-06-25 15:47 UTC
Labels: Bug, Fix committed
