### ISSUE TITLE
OpenELEC 5.0 - MP4 Playback Issues (slowdown, choppy playback)

### ISSUE THREAD

**Issue by sonicnkt** [OpenELEC/OpenELEC.tv#3763] opened 2015-01-09 12:20 UTC
Hi,
im testing the new OE5.0 now for several days on my AMD Kabini System and even tho the system crashes and random reboots of 4.2.X are gone i came across several Mp4 files that have playback issues (some youtube videos as well using youtube addon).

The playback is verry choppy and audio is out of sync.
It also slowsdown the whole kodi system if you play these files in the background and navigate through the menu. (FPS dropped from 60 to 5-8) and CPU Usage shows 100% on one core 

These files play fine on my PC using VLC or Kodi so it is a OE5.0 related Problem or atleast OE on AMD Kabini.
I tested playback using VDPAU acceleration aswell as without, no change.

XBMC-Log of the playback:
http://pastebin.com/hV0C6PMA

Here is a short test file uploaded by lordalibaski on the forums:
https://www.sendspace.com/file/ws9o23
Codec Info:
http://pastebin.com/tRsUPD6E

**Comment by fritsch** [comment] 2015-01-09 12:25
Better:
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-5.0.0-fritsch2.tar
?

do a full backup of your data before. This build does not have all dvb-c /
dvb-t drivers and is for testing purpose only.

2015-01-09 13:20 GMT+01:00 sonicnkt <notifications@github.com>:

> Hi,
> im testing the new OE5.0 now for several days on my AMD Kabini System and
> even tho the system crashes and random reboots of 4.2.X are gone i came
> across several Mp4 files that have playback issues (some youtube videos as
> well using youtube addon).
>
> The playback is verry choppy and audio is out of sync.
> It also slowsdown the whole kodi system if you play these files in the
> background and navigate through the menu. (FPS dropped from 60 to 5-8) and
> CPU Usage shows 100% on one core
>
> These files play fine on my PC using VLC or Kodi so it is a OE5.0 related
> Problem or atleast OE on AMD Kabini.
> I tested playback using VDPAU acceleration aswell as without, no change.
>
> XBMC-Log of the playback:
> http://pastebin.com/hV0C6PMA
>
> Here is a short test file uploaded by lordalibaski on the forums:
> https://www.sendspace.com/file/ws9o23
> Codec Info:
> http://pastebin.com/tRsUPD6E
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3763>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by sonicnkt** [comment] 2015-01-09 12:40
Wow thanks for the fast reply...
I just tried the built and it fixes the playback issues...
but sadly the random reboot and crashes are back descriped in the first post of this issue:
https://github.com/OpenELEC/OpenELEC.tv/issues/3462#issuecomment-63182072

It literally crashed 5 seconds after i stopped the playback of the small test file :(

**Comment by fritsch** [comment] 2015-01-09 14:56
Good - or not good :-) - I will bisect the performance regression on sunday
- if and only if - time permits and then provide a build with that commit
reverted.

2015-01-09 13:40 GMT+01:00 sonicnkt <notifications@github.com>:

> Wow thanks for the fast reply...
> I just tried the built and it fixes the playback issues...
> but sadly the random reboot and crashes are back descriped in the first
> post of this issue:
> #3462 (comment)
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3462#issuecomment-63182072>
>
> It literally crashed 5 seconds after i stopped the playback of the small
> test file :(
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3763#issuecomment-69329340>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment] 2015-01-10 19:47
I wanted to bisect today. But I cannot reproduce on Ubuntu with Mesa 10.3
and kernel 3.17 ... so I am a bit out of ideas what is causing this. I even
run the OpenELEC kernel on Ubuntu with same config ... no issue there.

2015-01-09 15:56 GMT+01:00 Peter Frühberger <peter.fruehberger@gmail.com>:

> Good - or not good :-) - I will bisect the performance regression on
> sunday - if and only if - time permits and then provide a build with that
> commit reverted.
>
> 2015-01-09 13:40 GMT+01:00 sonicnkt <notifications@github.com>:
>
>> Wow thanks for the fast reply...
>> I just tried the built and it fixes the playback issues...
>> but sadly the random reboot and crashes are back descriped in the first
>> post of this issue:
>> #3462 (comment)
>> <https://github.com/OpenELEC/OpenELEC.tv/issues/3462#issuecomment-63182072>
>>
>> It literally crashed 5 seconds after i stopped the playback of the small
>> test file :(
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpenELEC/OpenELEC.tv/issues/3763#issuecomment-69329340>
>> .
>>
>
>
>
> --
>                    Key-ID:     0x1A995A9B
>                    keyserver: pgp.mit.edu
> ==============================================================
> Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by sonicnkt** [comment] 2015-01-12 13:04
Anything i can do to help?

**Comment by fritsch** [comment] 2015-01-12 13:10
Nope. I could not reproduce on Ubuntu, with the very same kernel and the very same mesa. I am out of ideas.

**Comment by sonicnkt** [comment] 2015-01-12 13:18
wondering why it works fine with official 5.0 but the test built or 4.2.X crash.
What is the difference? And why only small mp4 sd videos have playback problems..

It runs fine on ubuntu?

**Comment by fritsch** [comment] 2015-01-12 13:36
Difference:
Test-Build: Kernel 3.16.7
Official: Kernel 3.17.7

On Ubuntu all is fine, no matter if 3.17.7 or 3.16.7 is used. So I cannot proof the regression on a system that is not OpenELEC.

**Comment by jtossenb** [comment] 2015-01-13 08:33
Please use this video file https://dl-web.dropbox.com/get/hi10p_sample.mp4?w=AAC8qnXfS0xxWbd5Fc2bkvWxMxeqlUiSkL-Dxe5C5BDVyw&dl=1&_subject_uid=67600211
It is a small hi10p sample (so pure software decode is in use) and the regression is clearly observable. Kodi 14.0 plays this file fine with kernel <3.17, but with kernel >=3.17 CPU is struggling, the playback is only 1 fps (like a slideshow). I hope it helps.
My system is Arch linux on AMD 5350. Similar/same problem is described here http://forum.kodi.tv/showthread.php?tid=210759&pid=1855779

**Comment by fritsch** [comment] 2015-01-13 08:42
There is absolutely nothing to proof. I can reproduce, clearly well, but I have no idea what is causing it.

**Comment by bluefuzz** [comment] 2015-01-13 17:00
I've just been trying the testbuild posted above. It seems to fix the choppy playback problems I had as posted in https://github.com/OpenELEC/OpenELEC.tv/issues/3681 

I'm not getting any crashes either. I've never had any crashes though, only stuttering/choppy playback of some files. Live TV is also fine. Everything perfect now!

This is on a Shuttle XS35GS V3L - Intel Atom 1.86 GHz, AMD Radeon HD 7450 GPU, 4GB RAM.

If you need any logs or anything just say so.

Cheers
Ian

**Comment by sonicnkt** [comment] 2015-01-13 17:28
the crashes are only happening on AMD APUs (Kabini) as far as i know...

**Comment by squallpolska** [comment] 2015-01-16 21:18
I have the same problem. My CPU Athlon 5350.

The problem occurs when you need to use software decoding. Also, files encoded with h264 codec. With hardware acceleration is not the problem. Everything works smoothly.

**Comment by jtossenb** [comment] 2015-01-17 09:45
I performed some experiments on Ubuntu 14.10 with Kodi 14.0 using the sample file I suggested some days ago (https://dl-web.dropbox.com/get/hi10p_sample.mp4?w=AAC8qnXfS0xxWbd5Fc2bkvWxMxeqlUiSkL-Dxe5C5BDVyw&dl=1&_subject_uid=67600211).
I installed different kernels from http://kernel.ubuntu.com/~kernel-ppa/mainline/ and I found:
3.16.7-031607-generic - 24 fps (good)
3.17.0-031700rc1-generic - 10 fps (bad)
3.19.0-031900rc4-generic - 10 fps (bad)
So the problem occurs with the kernel 3.17-rc1 and it still persists.
The experience is not so bad as on Arch linux, but clearly observable.
I hope it helps someone to do the bisecting.

**Comment by fritsch** [comment] 2015-01-17 12:18
Yeah - depending on your hardware. I did that on my E350 and I cannot reproduce it with either 3.17.7 or  3.19 - we have to distinguish two things here. UVD performance clock non existent, which happens on Kabini and later and the pure SW problem we have on all chips.

**Comment by fritsch** [comment] 2015-01-17 12:20
As you can reproduce it that clearly, try to do a real bisect between 3.16 and 3.17-rc1 - that will find the offending commit. Should be quite easy on Arch.

**Comment by jtossenb** [comment] 2015-01-21 10:57
I've done the bisect and filed a bug https://bugs.freedesktop.org/show_bug.cgi?id=88658

**Comment by fritsch** [comment] 2015-01-21 11:54
Thank you very much!

Can you please link the patch that solved your issue? The patch in comment
30 seems to be obsolete?

2015-01-21 11:57 GMT+01:00 József Tossenberger <notifications@github.com>:

> I've done the bisect and filed a bug
> https://bugs.freedesktop.org/show_bug.cgi?id=88658
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3763#issuecomment-70818674>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by jtossenb** [comment] 2015-01-21 12:04
This is the patch that solved the problem: https://bugs.freedesktop.org/attachment.cgi?id=110024
It was never merged. In bug 84627 they finally issued a similar patch but only for 32-bit: http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a08b588e4199e4200d26027ffcdf3ab2fa906412

**Comment by fritsch** [comment] 2015-01-21 16:02
This won't fix the bug on E350 series which are also affected. That's make
me wondering.

2015-01-21 13:04 GMT+01:00 József Tossenberger <notifications@github.com>:

> This is the patch that solved the problem:
> https://bugs.freedesktop.org/attachment.cgi?id=110024
> It was never merged. In bug 84627 they finally issued a similar patch but
> only for 32-bit:
> http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a08b588e4199e4200d26027ffcdf3ab2fa906412
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3763#issuecomment-70825829>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by stefansaraev** [comment] 2015-01-21 17:03
what about always forcing flags &= ~RADEON_GEM_GTT_WC like on x86_32 ? :D /me hides

**Comment by fritsch** [comment] 2015-01-21 17:27
Lol. We need to ask Alex on IRC.
Am 21.01.2015 18:03 schrieb "Stefan Saraev" <notifications@github.com>:

**Comment by sonicnkt** [comment] 2015-01-21 18:52
So kabini can be fixed but the older E350 still have the problem?
can someone upload a precompiled OE Kernel Image for testing?

**Comment by fritsch** [comment] 2015-01-21 21:35
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-devel-20150121202904-r19895-g8618bcb.tar
<- This is a build from current openelec-5.0 tree with the patch you
linked, I replace the if (....) to if(1), so it will be active for all AMD
chips.

2015-01-21 19:52 GMT+01:00 sonicnkt <notifications@github.com>:

> So kabini can be fixed but the older E350 still have the problem?
> can someone upload a precompiled OE Kernel Image for testing?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3763#issuecomment-70897589>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by sonicnkt** [comment] 2015-01-21 23:37
thank you very much...
this fixed all the Problems on my Kabini 5350 based System.

No random crashes, and fast software decoding.

**Comment by ikweethetniet** [comment] 2015-01-22 12:44
Does it also fix the "slow playback"  issue with mpeg2/dvd/iso/img on a kabini platform? Or only with MP4?It seems that  these are played with  a crippled software decoder instead of VDPAU (just like the issue with MP4)
Or have you disabled VDPAU completely and use only software decoding?
(IIRC, the MPEG2 VDPAU option was not checked in the official openelec 5.0 build after a fresh install. Just as if the MPEG2 hardware decoding option was not recognized for VDPAU for some reason. Same could be true for MP4 but I can't recall)

My system:
Asrock AM1H-ITX (using on-board power supply + external 90W adapter)
AMD Athlon 5350
Kingston Valueram 2x4GB 1600MHz -> 2Gb assigned to GPU
64Gb SSD (Openelec)
4TB HDD SATA (movies)
2TB HDD USB3 (movies)

**Comment by sonicnkt** [comment] 2015-01-22 12:48
i havent tried mpeg2/dvd/iso/img yet only different codecs in mp4 containers... all those slow down the system with the official 5.0 and now play fine.
VDPAU is activated.
i can try a DVD later today but why dont try it yourself... the update to the last test build by fritsch worked fine without destorying anything :)

**Comment by phate89** [comment] 2015-01-22 12:54
DVD menus (and video launched from menus) are software decoded not hardware decoded so it's almost for sure the same problem

**Comment by ikweethetniet** [comment] 2015-01-22 13:10
@sonicnkt 
Thanks! I was going to try it tonight. But I'd like to know up front, otherwise I risk angry faces at home :-)
I'll probably do a fresh install because I'm now running 4.2.1 and I'm not sure if all apps are compatible with 5.0.

@phate89 

Huh? I'm a bit puzzled, do you mean that physical DVD's or images are always played using software decoding?

I'm new to Openelec (assembled my system two weeks ago after having used a PCH-c200 for several years without complaints) and the first movie I played was a physical DVD. It really crawled on my system (~5fps) and soon noticed that hardware decoding was disabled for mpeg2. Since enabling mpeg2 didn't improve the situation, I switched back to 4.2.1. But unfortunately, I experience one or two reboots when playing mkv movies.
You can imagine that if those problems are solved with the test build of fritsch , my family will be very pleased  :+1:  :100:

**Comment by phate89** [comment] 2015-01-22 13:16
Yes dvds launched from dvd menu are software decoded. I think there is some problem with hardware accelerated menus. I don't know if navigating manually to the file and play that file solves it.

**Comment by fritsch** [comment] 2015-01-22 13:55
Can we keep this talk on topic, please - I get an email for every post. 

Please test the above build on all your hardware. I need Kabini, E Series Fusion, A Series, please.

**Comment by cg9999** [comment] 2015-01-22 17:05
Works fine and fixes slow playback issues on my Kabini 5350

**Comment by ikweethetniet** [comment] 2015-01-23 08:06
DVD playback is also fixed with this patch on an Athlon 5350 + AM1H-ITX
Haven't checked stability yet though.

**Comment by fritsch** [comment] 2015-01-23 08:10
Okay - so E-series left to go ... and no single idea there yet.

**Comment by Ruud68** [comment] 2015-01-24 09:58
Hi, just tested the development-build in this thread on a AMD E-350 cpu: vdpau enabled = artifacts, vdpau disabled is 8fps :(
If you need testing, I can help :)

**Comment by fritsch** [comment] 2015-01-24 10:06
artifacts is something new - which is not to be explained with that patch.

There is nothing to test anymore - I pushed the fix for kabini and aruba. Other cpus are not affected by this new patch.

We have no solution for the old E-series.

**Comment by macman88** [comment] 2015-02-03 04:08
I've been bisecting OpenELEC over the past few days on my E350 system (nt-a3500) and this is what I came up with:
```
15a508239922770989f42f495d3e1a47759d5046 is the first bad commit
commit 15a508239922770989f42f495d3e1a47759d5046
Author: Stephan Raue <stephan@openelec.tv>
Date:   Sun Oct 26 10:34:47 2014 +0100

    Mesa: update to Mesa-10.3.2
    
    Signed-off-by: Stephan Raue <stephan@openelec.tv>
```
I double-checked and mp4 playback is definitely smooth for me under the previous commit (cf1ec2e8d96ca521e00e9221b93334117ae51999) running Mesa 10.3.1.

**Comment by fritsch** [comment] 2015-02-03 07:20
Hui! thanks very much. I see three patches, that could cause the issue:
a) http://cgit.freedesktop.org/mesa/mesa/commit/?h=10.3&id=64c2bdc334ba472603b1e7cd2c3046cfbce285b6
b) http://cgit.freedesktop.org/mesa/mesa/commit/?h=10.3&id=c759d1b6bfbc15b044ef3f7cd590b6647c3670df
c) http://cgit.freedesktop.org/mesa/mesa/commit/?h=10.3&id=724f71ef3905289eee7b45955243fdc7dc5f1251


My personal tipp is c) Any change to revert them? You need to put the patch to the Mesa/patches directory like 0001-Mesa-revert-bla.patch

**Comment by fritsch** [comment] 2015-02-03 12:32
Can you try this build, please:
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-5.0.1.tar
Best regards
Peter

**Comment by macman88** [comment] 2015-02-03 14:23
Mp4 playback is smooth for me using that test build. 
I can try to take a look at those patches tonight.

**Comment by fritsch** [comment] 2015-02-03 17:36
Okay: what works here: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-5.0.1-revert3.tar

**Comment by bluefuzz** [comment] 2015-02-03 19:20
This last build seems to fix playback issues for me too (Radeon HD 7450).
Ian

**Comment by fritsch** [comment] 2015-02-03 19:49
@macman88 same for you?

Okay - then we have three patches left. I reverted all of them I pointed out before :-)

**Comment by indians810** [comment] 2015-02-03 19:50
I have a Foxconn nt-A3500 with the AMD E-350 Processor and Radeon HD 6310(integrated). I was having major skipped frames and artifacts like other people on OE 5.0.1 with this processor playing mpeg4 files. The last build has fixed the problem using the default video accelleration settings.  I have zero dropped and skipped frames now. I was pulling my hair out trying to get it working right. Weird thing was I would change the accelleration settings on the official 5.0.1 and actually get it to play properly and then I would stop that video and change nothing and then play the same file again and it would skip like crazy.  Very weird... THANKS!!!

**Comment by fritsch** [comment] 2015-02-03 20:29
We need sane testing, please. I still want to find out which of the patches. So every time you post here, please also post the link to the build you are currently running.

I will now prepare another build with only _one_ of those patches.

**Comment by fritsch** [comment] 2015-02-03 21:13
What works:

a) https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-5.0.1-1001only.tar
b) https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-5.0.1-1002only.tar
c) https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-5.0.1-1003only.tar

Please test.

**Comment by indians810** [comment] 2015-02-03 23:01
I've tested all three on my Foxconn NT-A3500 AMD E-350 machine. I used the same mpeg4 video files and default video acceleration settings for all. All were clean installs.
a) caused skiped frames 
b) no skipped or dropped frames (works)
c) caused skipped frames (dropped frames A LOT faster than the 'a' build)

**Comment by fritsch** [comment] 2015-02-04 07:06
Thank you very much :-). You have won :p 

See: https://github.com/OpenELEC/OpenELEC.tv/pull/3863 - I have pushed the patch.

For every one reading this, please keep: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-5.0.1-1002only.tar

I will remove the others from my download. This is final 5.0.1 with only the patch from the PR

**Comment by fritsch** [comment] 2015-02-04 08:50
@indians810 @macman88 I talked with michel daencer on #radeon and he told, that another approach should be prefered: Can you test: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-Generic.x86_64-5.0.1-mdaencer.tar

Thanks much

**Comment by macman88** [comment] 2015-02-04 14:52
Playback performance looks good to me on both the 1002only and mdaencer builds.  I don't see any difference between the two.

**Comment by fritsch** [comment] 2015-02-04 14:55
Thanks very much! Then I will choose mdaencers fix.

**Comment by bluefuzz** [comment] 2015-02-04 16:11
Mdaencer's build is fine for me too on Radeon HD7450.

**Comment by fritsch** [comment] 2015-02-04 18:11
Thx much, please spread the above mdaencer build arround for other radeon users. That patches will be in 5.0.2

**Comment by fritsch** [comment] 2015-02-04 18:11
Fixed via: https://github.com/OpenELEC/OpenELEC.tv/pull/3867

**Closed by fritsch** 2015-02-04 18:11 UTC

**Comment by indians810** [comment] 2015-02-04 19:05
The Mdaenencer build works fine for me too. Thanks for getting this sorted @fritsch and @macman88 !! Now to finally set up Helix...

**Comment by fritsch** [comment] 2015-02-06 07:32
http://cgit.freedesktop.org/mesa/mesa/commit/?id=a338dc01866ce50bf7555ee8dc08491c7f63b585 <- here, see the benchmarks :-) Factor 10 it did. Thanks very much again would not have happened without our users!

**Comment by kdschlosser** [comment] 2015-02-10 00:24
ummm not 100% I think. Have same issue on 5.0.2 with FoxConn at-5570 has a C-70 CPU and AMD Radeon HD 7290 wicked choppy video. live TV  works but that's about all.

**Comment by fritsch** [comment] 2015-02-10 11:46
Logfiles or it never happened ... this issue was reported to be fixed by 4 other users, including an C-70 tester on IRC.
