### ISSUE TITLE
Scaler broken in 5.0.7

### ISSUE THREAD

**Issue by shrubberies** [OpenELEC/OpenELEC.tv#4063] opened 2015-04-01 17:44 UTC
OpenElec 5.0.7
Cubox i 4pro

Playing anamorphic dvd (720x480) with 16x9 PAR produces ugly shear scaling on 5.0.7. Works correctly on 5.0.6

**Comment by fritsch** [comment] 2015-04-01 19:38
@wolfgar: I think this is a regression of the rewrite. Do you have an idea?

**Comment by fritsch** [comment] 2015-04-01 19:39
@shrubberies please post a ~20 MB sample somewhere that shows the issue.

and for next time, all logs are required that the documention ask you for, when opening such a bugreport.

**Comment by wolfgar** [comment] 2015-04-01 21:24
Hi Peter,
yes you are definitively right, it is very likely due to the new rendering...
As soon as the sample sample is available, I will have a look at it to fix
It should not be a big deal

**Comment by fritsch** [comment] 2015-04-02 06:49
@wolfgar thx very much in advance for looking into that. So now let's wait until @shrubberies provides the sample we need.

**Comment by shrubberies** [comment] 2015-04-02 16:27
I tried to do screenshots but when I invoke a screenshot kodi crashes and the resulting file is all purple.
Tested against 5.0.8 with same result.
Here is a log from 5.0.8
http://pastebin.com/TMeV26xV

I could take a photo of the screen if that would be helpful to you. The source material is a dvd bob 720x480 anamorphic 16x9 being scaled to 720p. It looks like unfiltered sheer scaling.

**Comment by fritsch** [comment] 2015-04-02 16:39
Make sure to verify with a completely fresh installation.

**Comment by shrubberies** [comment] 2015-04-02 16:55
Here is a VOB that displays the scaling problem
https://www.dropbox.com/sh/nrcx1roes9sca1o/AAD967Blfep3btDqhXLneKwVa?dl=0

I'll try again with a new install of 5.0.8

**Comment by shrubberies** [comment] 2015-04-02 17:58
Confirm that the bug persists a clean install of 5.0.8

**Comment by wolfgar** [comment] 2015-04-03 23:42
OK I have reproduced the issue but it is not as easy as I would have though
scaling is properly configured and the poor result seems to be only related to the GPU2D.
It is a little strange because the result when scaling between 720p and 1080p is good (at least good enough not to be noticed..).
I have to take a break for easter weekend but I will try to dig next week.
(We can easily scale differently this stream which is not demanding but then the question is which heuristics will allow to choose)

**Comment by shrubberies** [comment] 2015-04-04 17:48
Looking at this more closely, I found that the scaler is working correctly but the output is going through a deinterlace pass even though the input is progressive. Deinterlace is set to auto by default I believe and is invoked when this material is played. Manually setting "delinterlace video" to "off" produces the correct result and actually the output from the scaler looks quite good.  Sorry to send you down the wrong path. Maybe it will be easier to determine why the interlaced is invoked when its not needed.

**Comment by fritsch** [comment] 2015-04-04 20:36
Does this simple patch help:
```
From 418cdc101fa48501f36bb046e8807fbe02e78f62 Mon Sep 17 00:00:00 2001
From: fritsch <Peter.Fruehberger@gmail.com>
Date: Sat, 4 Apr 2015 22:35:27 +0200
Subject: [PATCH] IMX: Initialize m_deInterlacing member

---
 xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp | 1 +
 1 file changed, 1 insertion(+)

diff --git a/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp b/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp
index 7789e38..73cd25a 100644
--- a/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp
+++ b/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp
@@ -1277,6 +1277,7 @@ CIMXContext::CIMXContext()
   , m_fbVirtAddr(NULL)
   , m_ipuHandle(0)
   , m_vsync(true)
+  , m_deInterlacing(false)
   , m_pageCrops(NULL)
   , m_g2dHandle(NULL)
   , m_bufferCapture(NULL)
-- 
1.9.1
```

**Comment by fritsch** [comment] 2015-04-04 20:45
If I read the code correctly, it's just this initialization. It should not work until you "toggle" at least once. E.g. if you start with Deinterlace: OFF it should also deinterlace, but when you swap to "Auto" and back to "OFF" it works as expected. right?

**Comment by sraue** [comment] 2015-04-04 23:22
@shrubberies can you please test http://snapshots.openelec.tv/test/OpenELEC-imx6.arm-devel-20150405011321-r20184-ge3ddf83.tar and report back?

**Comment by wolfgar** [comment] 2015-04-05 23:55
@shrubberies thanks for the update : you are definitively right, the issue has to do with improper interlacing probing. To me, current fix may not be enough : refer to to https://github.com/xbmc/xbmc/pull/6878

**Comment by fritsch** [comment] 2015-04-06 07:51
I think it's cause of NTSC dvd content. I did not find another solution besides checking for 480 && 720 and assume that interlace flag is wrong: https://github.com/fritsch/xbmc/commit/d298b01cb3d613cb81db8c85dc181d7d0d838006

@sraue will do another build

**Comment by sraue** [comment] 2015-04-06 11:44
another build, @shrubberies please test: http://snapshots.openelec.tv/test/OpenELEC-imx6.arm-devel-20150406131803-r20184-ge3ddf83.tar

**Comment by fritsch** [comment] 2015-04-06 11:54
@sraue thx much, I decided against the referenced commit and instead used: https://github.com/fritsch/xbmc/commit/471b1c70d5f882414fb7fbbbd8cc2386e128f55e which is in sraue's build.

From the log:

```
11:45:10 T:1968807936 WARNING: Content is progressive but flagged interlaced
``` 
http://sprunge.us/aNRW

**Comment by shrubberies** [comment] 2015-04-06 17:12
Build 20150406131803-r20184-ge3ddf83 from sraue's post above plays the content correctly. Fix looks good. Previous build - 20150405011321-r20184-ge3ddf83 did not look different from 5.0.7 - 5.0.8- still deinterlacing. Thanks everyone for your efforts to address this.

**Comment by sraue** [comment] 2015-04-06 17:53
thanks much @shrubberies for the report

**Comment by fritsch** [comment] 2015-04-08 20:56
We won't keep that patchset in stable kodi. This caused regressions for LiveTV stations that send some progressive frames between their fields.

So in future, you need to explicitely disable deinterlacing for such files. In the longterm future we plan on replacing the wrapper we are currently using, so that might work automatically.

**Comment by shrubberies** [comment] 2015-04-09 15:33
I don't want to take up more of your time with this. I realize this is a case where the media flags are wrong and I've read through the linked discussions. I'm not clear on why  <=5.0.6 worked and other platforms work (rpi,android) but 5.0.7+ fails.

**Comment by fritsch** [comment] 2015-04-09 15:39
5.0.6 worked cause Deinterlace was set to "Off" by default.

**Comment by chewitt** [comment] 2015-12-23 11:59
@shrubberies @fritsch - I'm working through old tickets looking for updates. Is this still an issue on OE 6.0.0 or can we close?

**Comment by chewitt** [comment] 2015-12-27 14:01
Closing due to lack of update. Thanks.

**Closed by chewitt** 2015-12-27 14:01 UTC
Labels: regression
