### ISSUE TITLE
[performance] XBMC plugins are compiled each time they are used

### ISSUE THREAD

**Issue by bitplane** [OpenELEC/OpenELEC.tv#3335] opened 2014-06-21 23:42 UTC
XBMC plugins are compiled every time they are executed (no pyo file is created upon execution), while pyo files distributed with plugins are ignored. This means that large plugins on slower/embedded systems have a compilation overhead on directory navigation, in the order of several seconds.

To prove this, create a file with a compile-time warning and notice how the warning is logged every time the plugin is executed. For example:

    def log_compile_warning():
        from time import *

If this is in your plugin's main file then you'll see a `SyntaxWarning` in xbmc.log every time the plugin is executed. If it's `import`ed by your plugin's main file then it will only be logged the first time the plugin is executed.

**Comment by stefansaraev** [comment] 2015-05-06 10:11
it's not a bug. default.py is special. I'll just close this ;)

**Closed by stefansaraev** 2015-05-06 10:11 UTC
Labels: Kodi
