### ISSUE TITLE
Wandboard support in imx6 project

### ISSUE THREAD

**Issue by xoddark** [OpenELEC/OpenELEC.tv#3653] opened 2014-11-30 16:01 UTC
Hello, I like to see the support of Wandboard in the imx6 project of OpenELEC,

I have started to add this, but I'm block by the u-boot management.

My changed are based on the imx6-final branch from vpeter4.
You can look-at this change here : https://github.com/xoddark/OpenELEC.tv/tree/wandboard_support_wip_2

If I install OpenELEC with the create_sdcard script, when I start the wandboard I have nothing on the serial output.
If I build u-boot from upstream like in this page : https://eewiki.net/display/linuxonarm/Wandboard#Wandboard-Bootloader:U-Boot,
and write u-boot.imx on the sdcard I have this output from u-boot on the serial console :
```
U-Boot 2015.01-rc2-00086-g38cd8c4-dirty (Nov 30 2014 - 15:05:22)
   
CPU:   Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: Wandboard
I2C:   ready
DRAM:  2 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
*** Warning - bad CRC, using default environment
   
auto-detected panel HDMI
Display: HDMI (1024x768)
In:    serial
Out:   serial
Err:   serial
Net:   FEC [PRIME]
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
Checking for: /uEnv.txt ...
reading /uEnv.txt
310 bytes read in 14 ms (21.5 KiB/s)
Loaded environment from /uEnv.txt
Checking if uenvcmd is set ...
Checking for: /boot/uEnv.txt ...
** Invalid partition 3 **
** Invalid partition 4 **
** Invalid partition 5 **
** Invalid partition 6 **
** Invalid partition 7 **
MMC: no card present
SD/MMC found on device 1
Checking for: /uEnv.txt ...
MMC: no card present
** Bad device mmc 1 **
Checking for: /boot/uEnv.txt ...
MMC: no card present
** Bad device mmc 1 **
MMC: no card present
** Bad device mmc 1 **
MMC: no card present
** Bad device mmc 1 **
MMC: no card present
** Bad device mmc 1 **
MMC: no card present
** Bad device mmc 1 **
MMC: no card present
** Bad device mmc 1 **
MMC: no card present
** Bad device mmc 1 **
```

And the board faile to boot.
I'm not very familiar with u-boot, someone have an idea to help me ?

Thank you.

**Comment by jpulz** [comment] 2015-01-30 14:12
@SyedAmerGilani : I donwloaded your image and tried it on my wandboard quad. Everything is running smotth but i found two problems.
1) If there is a microSD card plugged into the second microSD slot, the system will not boot end end with a recovery console. Message on the serial line is something like "unable to mount root device". If i unplug the second card it boots just fine. I can insert the card again afterwards and it is recognized and useable.
2) Bluetooth is not working at all. Kodi says "No Bluetooth adapter found". In the kernel messages is some error regarding bluetooth logged.

I don't have the correct error messages for both problems as i'm away from my wandboard.

Will there be a new image with the latest imx6 related changes that hit the official OpenELEC.tv repo lately?

**Comment by xoddark** [comment] 2015-01-31 14:05
I have tried the image build by SyedAmerGilani, and tried to build my version, it never work correctly.
OpenELEC boot, kodi start, but I don't have ouput on hdmi output.
I have a Wandboard quad rev C1 linked with dvi adpter to a computer monitor who work in 1680*1050). I have no idea of what is wrong.
Someone can help me ?

**Comment by synportack24** [comment] 2015-01-31 14:42
I did a build of SyedAmerGilani OpenELEC for my C1 quad. Everything seemed to work just fine apart from the bluetooth. I also tried connecting the board to my TV via HDMI -> DVI and also got nothing to show (HDMI -> HDMI worked just fine). I know that HDMI-> DVI has been problematic there are several forum posts about this over on the wandboard forum as well as one from the old google forum: 
https://groups.google.com/forum/#!topic/wandboard/eQ3PaEe5uwo

**Comment by synportack24** [comment] 2015-02-21 19:01
I'm using SyedAmerGilani on a C1 wanboard and a libcec-client -l shows that there no devices found.  I was wondering if anyone had any luck with this?

**Comment by xoddark** [comment] 2015-02-23 12:42
I don't have a TV compatible with CEC, so not tested for me.

**Comment by MCOberle** [comment] 2015-05-04 16:34
@xoddark and @SyedAmerGilani: I am trying to bring openElec to RIoTboard. I have managed to adjusted u-boot and the kernel start but gets stuck at 
[  OK  ] Reached target Kodi Mediacenter Interface.
with no HDMI output.
Was this the same for you before you took another DTB?
Did you change anything else apart from the DTB? Looking into the patch for wandboard it seems like you were also changing something with the video driver?

**Comment by vpeter4** [comment] 2015-05-04 20:00
@MCOberle: which kernel exactly are you using?

**Comment by MCOberle** [comment] 2015-05-05 18:14
I have tested openELEC Kernel 5.02 and 5.08. 
My DTB is from mainline KERNEL 3.19.

**Comment by xoddark** [comment] 2015-05-05 18:48
@MCOberle : I had the same problem when the screen linked to my board don't support fullHD.
For the wandboard, the output screen resolution is hardcoded in the file uEnv-wandboard_x.txt.
.

**Comment by vpeter4** [comment] 2015-05-06 09:04
@MCOberle: I would suggest you to use whole kernel from one (verified) source which actually works. Like from [this](http://www.element14.com/community/community/designcenter/single-board-computers/riotboard/blog/2014/07/31/upgrading-riotboard-with-kernel-31017-linux-host) post.
branch [embest_imx_3.10.17_1.0.0_ga](https://github.com/embest-tech/linux-imx.git)

Don't mix kernel and dtb. Later you can port this dts to kernel used by openelec.

**Comment by Chris81T** [comment] 2015-05-13 06:19
Hi,
at first thank you all to make it possible to get openelec running at the wandboard quad. I have downloaded months ago an openelec image (development version) for my wandboard and the maintime it works fine. After two, three weeks I need 3 or 5 times to get openelec started.also it is possible, that Every settings are resetted. Normally I wont start to customize the system. My aim is to have a solid running media center. 

So can somebody tell me, if there is a newer image of openelec running at the wandboard device? If someone can give a link would really be nice :) 

Thank you! 

PS:
Is it possible that in the near future openelec officially will support the wandboard devices, so we can simply download from the official site directly?

**Comment by vpeter4** [comment] 2015-05-13 07:03
Little bird told me the reason not including such support is bottom part of http://openelec.tv/

**Comment by MCOberle** [comment] 2015-05-13 09:56
@vpeter4 The source you are refereing to does not include HDMI output support. Anyway ther is apparently a later version that supports HDMI output. I would then try to decompile the DTB of that version and the DTB of udoo or wandboard and try to compare - would that be the way to go?

**Comment by MCOberle** [comment] 2015-05-13 10:00
@xoddark: The connected device supports fullHD - I have also tried other resolutions but that does not help. I think the problem is the DTB.

**Comment by xoddark** [comment] 2015-05-13 10:46
@MCOberle Do you use an hdmi -> dvi convertor ? It's can be a source of problem.

**Comment by stefansaraev** [comment] 2015-05-13 10:49
> Little birdie told me the reason not including such support is bottom part of http://openelec.tv/.

care to explain?

thanks

**Comment by vpeter4** [comment] 2015-05-13 11:11
I think it's self-explaining.

**Comment by MCOberle** [comment] 2015-05-13 11:15
@xoddark I am connecting straight from hdmi port of riotboard to hdmi of my (fullhd) tv.

**Comment by stefansaraev** [comment] 2015-05-13 11:17
> I think it's self-explaining.

I think it is not. explain or stop spreading nonsense. thanks.

**Comment by vpeter4** [comment] 2015-05-13 11:21
Money of course :-) What else.

**Comment by stefansaraev** [comment] 2015-05-13 11:22
what money, can I have some? who pays?

**Comment by stefansaraev** [comment] 2015-05-13 11:23
so, you are basicaly saying "a competitor pays openelec team to NOT support other devices" ?

**Comment by xoddark** [comment] 2015-05-13 11:35
I do not know enough about the organization of the team OpenELEC to judge.
But I did not understand and was frustrated by the lack of update (merge or comment) on this pull request : https://github.com/OpenELEC/OpenELEC.tv/pull/3645

**Comment by xoddark** [comment] 2015-05-15 13:10
Good to see the patch form imx merged last days.

I still hope to integrate Wandboard management in OpenELEC. With my actual version We need different image for different board, which is not ideal. And the actual version of uboot used by OpenELEC is a version from solidRun.

But some work are done to upstream Cuboxi and Humiboard management in uboot.
And an update of uboot wandboard management are in progress to use SPL.
I like to replace the custom uboot version by the upstream, it's should be ok for Wandboard and Cubox (soon ?), but I don't know if the TBS matrix and the Udoo device have management upstreamed.

Last version of my work to manage multi device in mx6 project : https://github.com/xoddark/OpenELEC.tv/commits/imx6_multi_devices
The result is one tar for update, and one image by device (uboot are different).
What do you think to have several image file for different imx6 device ?
I don't know if it's should be possible to have SPL management for multiple imx6 board (Cuboxi, Wanboard, TBS matrix, udoo, ...)

Thank you.
PS: Sorry if my English are not correct ^^, You can correct me, or ask me what I meant.

**Comment by vpeter4** [comment] 2015-05-15 13:22
I don't think we can expect one bootloader which would support all possible devices. Much easier (at least for now) is to have separate images for different systems. And matrix doesn't need image - only tar archive because it is uses MfgTool to transfer image to integrated eMMC modul.
Udoo and Matrix works with mainline u-boot 2015.xx (already tested) but there is no support for cuboxi. So we always will have a problem. I port all required changes for udoo and matrix to solidruns u-boot version. That's why for now I don't need separate u-boot version. So if we want to use different u-boot versions for different systems we have another problem - how to use two similar packages at the same time.

**Comment by xoddark** [comment] 2015-05-15 13:49
@vpeter4 ok for the multiple image. At list one image for all wandboard instead of two is better.
For cubox, I don't know if it's already usable, but Fabio Estevam work on upstreaming cubox-i u-boot management. I have to test when I would have a moment.

**Comment by vpeter4** [comment] 2015-08-16 10:16
Lately I add SPL support for udoo. Because I was testing different versions of u-boot I was looking for one simple way of using multiple u-boot versions in single openelec image. So I think on one simple solution (probably not the elegant but it works well).
I add another u-boot package (u-boot-udoo) and manually unpack u-boot sources. Package is build at the end from OEM. Created u-boot.imx or SPL/u-boot.img is renamed and copied to original u-boot build . When creating final openelec image the correct bootloader is used.
One problem solved :)

**Comment by chewitt** [comment] 2015-12-22 04:53
I'm closing the ticket due to lack of update and on advice from @vpeter4 who continues to track imx6 efforts on behalf of the OE staff. This does not mean we refuse to add Wandboard in the future, but until bootloader things level become more standardised a community build is a better option. Thanks.

**Closed by chewitt** 2015-12-22 04:53 UTC
Labels: feature-request

**Comment by vpeter4** [comment] 2015-12-22 08:09
Until there is a clear way how to proceed with imx6 project (which kernel, how to combine multiple u-boot's, ..) there is not much to do.
But because there is not much imx6 users out there seems this project is mostly in stagnation.
