### ISSUE TITLE
OpenELEC 5.0 issues on freescale cubox-i4pro

### ISSUE THREAD

**Issue by ylorig** [OpenELEC/OpenELEC.tv#3844] opened 2015-01-27 20:51 UTC
hello,

i'm reposting my post from the solidrun fourm.
Help will be appricated.
thank you

"Hi all,

Iv'e been using OPENELEC for my i4pro with last few releases and it was working fine.
Since the last updat to 5.0.0 i have experince a few problems:
- My remote logitech keyboard and mouse stops working after awhile, reset solve the problem until it occurs again. this happend also to a freind with a remote logitech keyboard and openelec 5.0.0.

- I'm using SPDIF sound and every now and then the sound output just changes to HDMI and i have to switch it back.

- Libary scaning isn't working well with my videos on my NAS, it detects the TV show but not the files and i have to scan it manually for each file.

Any idea, comments, ect'

Thnx!!! :?:  :?:  :?:"

**Comment by tunf** [comment] 2015-02-23 21:17
How about the 5.0.2? 
1. remote, what do you reset, where is the log?
2. what is every now and then? 
3. library scanning is working and is not a bug.

**Comment by chewitt** [comment] 2015-02-24 04:41
I'm closing the ticket because end user support is provided via the forums not our development bug tracker.

**Closed by chewitt** 2015-02-24 04:41 UTC
Labels: Invalid
