### ISSUE TITLE
OpenELEC 5 freeze on "shot" beyond the end at seeking

### ISSUE THREAD

**Issue by beta-tester** [OpenELEC/OpenELEC.tv#3797] opened 2015-01-15 13:53 UTC
hi, i have OpenELEC 5.0.0 / Kodi 14 installed on my Raspberry Pi.
i noticed, when i seek chapter wise or seek time portion wise up to the end of a video it may happen, that the player shoots beyond the end of the video.

for example: a video has a length of 1:23:45 and i seek chapter by chapter or seek time (+30s or +60s) and it can happen that i reach the end and shoot beyond the end e.g. 1:23:50.

at that moment, the last showed previously frame of the stays freezed on the screen.
i have to stop the playback manually by keyboard/remotecontrol. and restart the play list again by hand... normally the next following video should start to play when the previous reached its end.

the video playback is configured to play the next video of the list, when the previous video is finished.

**Comment by stefansaraev** [comment] 2015-01-15 14:15
please [read](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md)

**Comment by beta-tester** [comment] 2015-01-16 12:55
sorry.
what you was the exact point if invalidate the report?
i searched the bug tracker for that issue, but i did not found an issue with the same behaviour - maybe i searched not deep enough.
i used the latest official release for Raspberry Pi, so version, build / arch is given and known.
i did not used a unstable developent build and i did not compiled my own build - is it known and fixed already?
or is it invalid because i did not provide a log file? that i can provide it wanted...

can you please give me a hint.

**Comment by mrdominuzq** [comment] 2015-01-16 14:57
It is also importent to provide logs for debugging. A zip file can be found in the logfiles samba share, this will contain all the logs needed.  :)

**Comment by beta-tester** [comment] 2015-01-16 19:15
here the link to the log files...
http://ge.tt/15rwfi82/v/0 

at 18:52 (between line 663 and 664 of 01_kodi.log),
i seeked beyond the of the video and the the video freezed.

i changed the settings to enable debugging information in the log.
unfortunately, there is no entry in the log, that shows up any user interaction.
after enabling the debugging log, i rebooted the system again.

now i tried to reproduce the behaviour, with no success.
maybe it only happens when the player was playing a couple videos before in a row.
i will try it tomorrow, then i will hopefully have a more detailed log file that shows up the reason of the problem.

**Comment by beta-tester** [comment] 2015-01-17 15:36
ok, i let the playback on for a couple of videos and now i could reproduce that behavior...
this time with detailed debugging information in the log file.
at 16:01:24 (line 6760) i over shoot beyond the end of the current video by chapterseeking, and the video freezed/stopped without further action - normally it should start the next video automatically, but it doesn't.
i waited for 1 minute, bewore is stopped the video by hand and created the logfiles.
http://ge.tt/9llWfl82/v/0

so it seems the it takes time, before the behaviour occurs...
i can not reproduce the behavoiur when openelec was startet just before.
i can reproduce the behaviour, when couple of videos were played before in a queue.
when it happened, it looks like the video is paused (CPU and CPU KODI usage is less than 10%), but nobody paused the video by any interaction... what i did was seeking beyond the end of video...
the normal behaviour is starting the next video.

**Comment by beta-tester** [comment] 2015-02-16 18:10
ok, 
with OpenELEC 5.0.3, i still have the problem with the freezed playback with shooting bejond the end of video...
http://ge.tt/6UoWdaA2/v/0

in the **kodi-log**
at time **13:44:36**, there is the last log of the previous video1
(i started it, and leted it run)
kodi is setted up to play the next video in the list automatically after finished the current video.
at **15:18:45** the playback of video2 started.
at **15:25:31**, i started to seek chapter by chapter until kodi shot beyond the end of video (by using my TVs remote control - via HDMI CEC).
after that, the playback freezed with the last showed frame and stayed freezed.
at **15:35:23**, i started to bring the kodi onscreen menu with the play, pause, fast forwared/backward tileline and cover image on to the screen.
on the screen, the menu contols said, that kodi is still in playback mode.
i toggled from playback to pause back and forth, but the video still stayed at the last showed frame.
at playback, the debug onscreen information showed **CPU-KODI 99.12%** at freezed pause, and it was **CPU-KODI 12.32%** at freezed playback.
the onscreen display showed in the top left corner `19/19 (Chapter 20)`, and at the right top corner the video timestamp was at `1:40:36 - 1:37:58`...

**BTW: i never was able reproduce that behavior after starting a video freshly, by my own interaction...
it is only possible to reproduce after kodi started one or more following video(s) automatically.
(playback settings are to continue with the next video in list, if the current video ends automatically)**

i hope somebody will notice that thread, even it is marked as `invalid`
(why is it still marked like this ?)

**Comment by beta-tester** [comment] 2015-02-20 17:33
an additional notice:
in case, the video is freezed like described before, i notices, if i try to seek backwards from the freezed frame, the video seekes a portion backwards, but then the playbach run in to a loop if few seconds (ca. 3second loop). it is no normal playback anymore.

**Comment by popcornmix** [comment] 2015-02-21 19:34
@beta-tester can you provide a sample file and instructions of exactly what I need to do to reproduce the issue?

**Comment by beta-tester** [comment] 2015-02-22 13:58
video files seems to make no matter.
MKV, mp4, SD resolution, HD resolution, 24fps, 25fps.
all content is converted by using Handbrake 0.9.9 or 0.10.0 from Handbrake.fr - used built-in high profile template, commonly included, if available, native language and one forign laguages and its subtitles.
or it is video content **downloaded** from youtube (mp4/flv) and saved locally to my NAS for later watching.

i have setted up OpenELEC/Kodi like this:
"System"->"Settings"->"Video"->"Playback"->"Play the next video automatically"->[X] (enabled)

"Movies"->"Title"->(crawl to a video somewhere in the middle of the list)->"Play only this"

let the video playback untouched until it ends and the next video starts automatically
 wait some few minutes, then start to seek chaper by champter ([UP]-key on remotecontrol or [UP]-key on keyboard) until you seeked **beyond** the current video.

normally the next folllowing video should start, but not here... you will see a black screen or the last showed frame from before seeking beyond.

it doesn't matter if the videos are marked as watched or unwatched.

when the video is freezed -> CPU0:8.0% (CPU-KODI: 7.92%)
the user interface is fully responsable...
when you now pause the freezed video -> CPU0: 100% (CPU-KODI 98.30%)
when you to in playmode ->CPU0:8.0% (CPU-KODI: 7.92%)
when you seek backwards there are different behaviour. 
- it will just reached close to a position of the end of video -> the video ends and the next video starts automatically.
- it will seek more far backwards and playback begins to kind of weird loop some portion of the video beginning from the point seeked to (~3 second)

**Comment by chewitt** [comment] 2015-08-20 12:20
closing due to length of time with no update

**Closed by chewitt** 2015-08-20 12:20 UTC

**Comment by beta-tester** [comment] 2015-08-21 07:37
it is not updated for that long time, because nothing changed! :(
the playback still freeze on seeking...
it also happens on seeking for video streams (netzkino, clipfish add-ons)
current version: OpenELEC 5.0.8 for Raspberry Pi 2

open a Video stream, and seek by using your TV remote
control (CEC Adapter DevId:1001, VenID: 2708, class:cec, version: libCEC2.2.0-firmware v1),
(up button for big jump seeking, right for smaller seeking)

**Comment by fritsch** [comment] 2015-08-21 07:52
As a beta-test it would be time to check if beta3 still has this issue.

2015-08-21 9:37 GMT+02:00 beta-tester <notifications@github.com>:

> it is not updated for that long time, because nothing changed! :(
> the playback still freeze on seeking...
> it also happens on seeking for video streams (netzkino, clipfish add-ons)
> current version: OpenELEC 5.0.8 for Raspberry Pi 2
>
> open a Video stream, and seek by using your TV remote
> control (CEC Adapter DevId:1001, VenID: 2708, class:cec, version:
> libCEC2.2.0-firmware v1),
> (up button for big jump seeking, right for smaller seeking)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3797#issuecomment-133316115>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by beta-tester** [comment] 2015-08-21 15:21
the issue definitely exist in http://ftp.fau.de/openelec/OpenELEC-RPi2.arm-5.95.3.img.gz
i just wrote the image to a 16GB SD card, booted OpenELEC 5.95.3,
installed video addons (clipfish, netzkino, vimeo, youtube)
opened youtube addon and searched for "Eevblog", started the EEVBlog781, just after start, i pressed tree times the up button on the TV's remotecontrol to seek big steps forward an the video get stuck at 20:05 - picture freeze.
i can stop py pressing the stop button.

**Comment by chewitt** [comment] 2015-08-21 15:29
Please test with another pi distro. If this exists in e.g. osmc then the issue needs to be reported to Kodi devs via their forums. If it is not present in other distro's we will reopen the ticket.

**Comment by MilhouseVH** [comment] 2015-08-21 15:30
Please try this [nearly final build](http://forum.kodi.tv/showthread.php?tid=234678) from @popcornmix, based on latest firmware and Kodi 15.1. You should be able to upgrade using the tar file dropped into the "Update" folder.

**Comment by beta-tester** [comment] 2015-08-21 15:58
i just tried "OpenELEC-RPi2.arm-6.0-devel-20150816180308-#0816b-g75e1b35.img.gz"
exactly the same behaviour.
1. wrote image to SD,
2. boot up RPi2 into OpenELEC
3. Video -> AddOn -> More -> Youtube -> intstall
4. Video -> Addon -> Youtube -> Search -> "eevblog"
5. start found video "EEVBlog 781 ..."
6. seeked >=3 times forward on TV's remote control to seek big steps forward
7. video got stuck at 20:05

**Comment by beta-tester** [comment] 2015-08-21 16:19
just tried "OSMC_TGT_rbp2_20150628.img.gz"
exactly the same behaviour.
1. wrote image to SD,
2. boot up RPi2 into OpenELEC
3. Video -> Video-AddOn -> Get More... -> YouTube -> Intstall
4. Video -> Addon -> YouTube -> Search -> "eevblog"
5. start video "EEVBlog 781 ..."
6. seeked >=3 times forward on TV's remote control to seek big steps forward
7. video got stuck at 20:03

hmm... it is a kodi (or RPi) thing...

**Comment by beta-tester** [comment] 2015-08-21 16:25
question: to report kodi issues... do i have to report it to github.com / xbmc / xbmc ... ? or is this a dead end?

**Comment by CvH** [comment] 2015-08-21 16:36
@beta-tester 
http://trac.kodi.tv/

**Comment by beta-tester** [comment] 2015-08-21 16:46
referenced from here to there http://trac.edgewall.org/ticket/12178

**Comment by popcornmix** [comment] 2015-08-21 22:04
I've just tried this and see the issue reported.
I've also tried this on x86 linux and the problem is there too.
So, not Pi specific and not openelec specific.
Either open a http://trac.kodi.tv/ ticket, or report on the general support forum:
http://forum.kodi.tv/forumdisplay.php?fid=228

**Comment by beta-tester** [comment] 2015-08-22 20:04
ok, reported now at http://trac.kodi.tv/ticket/16211
i didn't remember that i already had an account for that, so no need to create my 10'th millions and one account ;) (only resetted my forgotten password)
