### ISSUE TITLE
nVidia Cards does not Work on OE (Stuck at Syslinux)

### ISSUE THREAD

**Issue by RefleX-mrl** [OpenELEC/OpenELEC.tv#4372] opened 2015-10-09 10:42 UTC
Hi together,

unfortunately my nVidia Graphic Cards does not work. I get the Bootscreen from Mainboard, then it stucks at "Syslinux" with blinking cursor.

BIOS is set to PCI-Express already. Got the same Problem with a brand new GT 730 as well as a brand new GT 610. SSH is still enabled. Updating to newer & older Generic Builds does not affect the issue. Deleting guisettings.xml does not help as well.

My System:
asrock fm2a88m extreme4+
AMD A-10 5800k
8 GB RAM
Cine S2 6.5 DVB-C
256 GB SSD
1 TB HDD
Power Supply: beQuite 430W

Installation via USB Stick works, Issue is still there after Reboot.

When setting BIOS to "Onboard" and Plug HDMI into Onboard Slot it boots fine.
Using latest BIOS version.

**Comment by lrusak** [comment] 2015-10-09 16:52
I would think that the problem is a race between your onboard graphics and your discrete card, however, nvidia should take priority over any other graphics driver.

I will need to see logs to see what is happening
http://wiki.openelec.tv/index.php?title=OpenELEC_FAQ#Support_Logs

**Comment by chewitt** [comment] 2015-11-23 14:45
closing.. if this is still an issue please start a forum thread to investigate

**Closed by chewitt** 2015-11-23 14:45 UTC
Labels: need-more-information
