### ISSUE TITLE
StartUp Issue with Xorg

### ISSUE THREAD

**Issue by dayton967** [OpenELEC/OpenELEC.tv#3026] opened 2014-03-18 03:13 UTC
With the AMD Fusion version of Openelec 3.2 and previous, if the monitor came up after the system, it normally would start Xorg.  The Beta's now currently crash, where the monitor is not found, upon reboot with the monitor running it works without problem.

**Comment by chewitt** [comment] 2015-12-16 13:20
closing as we no longer support 3.2.x builds - if the issue is still a problem with 6.0.x please open a thread in the forums

**Closed by chewitt** 2015-12-16 13:20 UTC
