### ISSUE TITLE
Openelec Kodi crashes/deadlock when streaming videos

### ISSUE THREAD

**Issue by BigPeltch** [OpenELEC/OpenELEC.tv#3925] opened 2015-02-18 23:46 UTC
I just installed Openelec on my HTPC, when I play videos it quickly crashes/deadlocks. The screen goes blank and the computer remains on. Also, I could not get sound through HDMI and when I attempted to increase the volume of whatever videos I was playing it did crashed/deadlock, I only got sound when I connected to my receiver using the 1/4 inch jack from my motherboard. My system specs are as follows:

 OS: [Stable] OpenELEC 5.0.2 (x86_64) Diskimage (Installed using a bootable USB)
ADM Phenom II FX 3300 @3.3ghz
ASUS M4A87TD/USB3.0
4Gb Munchkin Redline @ 1600
Kingston SSD Now V300 120Gb
Powercolor HD 6850

I have enabled debugging log, however, I do not know how to get these logs and post them on this issue report. When I first installed it, it seemed to stall at 87%, saying attempting to remove Temp files.

If anyone can give me a hand in fixing this issue it would be extremely appreciated. Until then, I will reattempt re-instaling to see if it fixes it.

**Comment by fritsch** [comment] 2015-02-19 07:56
Please provide what you were asked for before entering this dev space: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

**Comment by BigPeltch** [comment] 2015-02-19 19:06
Alright, learning lots here and just figured out how to use Sprunge! here at the URLs to both the Kodi.log and the Kodi.old.log:

http://sprunge.us/dhDg
http://sprunge.us/WiHJ 

I would really like to get the video issue fixed so I can enjoy my OpenElec system. Ultimately, I would like to be able to use sound through HDMI to my TV.

Thanks again in advance, your help is really appreciated.

**Comment by BigPeltch** [comment] 2015-02-19 19:37
I just tried to play another video through an add-ons. The video is called App/ritif de Hannibal. Samething again, video starts with sound then freeze, sound continues shortly and then the whole thing deadlocks, albeit the computer stays on.

http://sprunge.us/WNAP
http://sprunge.us/YBjf

**Comment by fritsch** [comment] 2015-02-19 19:45
Can you reproduce this with non illegal addons?

**Comment by BigPeltch** [comment] 2015-02-19 19:59
Sorry, did not think of this. Would it be ok if i would connect my external HDD and try to play a movie file that I legally own?

**Comment by fritsch** [comment] 2015-02-19 20:11
Jep, or use a sample, e.g.:
http://solidrun.maltegrosse.de/~fritsch/720p50_h264.mp4

2015-02-19 20:59 GMT+01:00 BigPeltch <notifications@github.com>:

> Sorry, did not think of this. Would it be ok if i would connect my
> external HDD and try to play a movie file that I legally own?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3925#issuecomment-75124534>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by BigPeltch** [comment] 2015-02-19 20:22
Alright working on it.

**Comment by BigPeltch** [comment] 2015-02-19 20:39
I downloaded, your sample (called Friscth.mp4) and attempted playing it on my HTPC, again, it started then deadlocked. Again, Kodi.log and Kodi.old.log:

http://sprunge.us/jVOR
http://sprunge.us/HcLU

**Comment by fritsch** [comment] 2015-02-19 21:05
Video -> Acceleration: Decoding-Method: Software

please

2015-02-19 21:39 GMT+01:00 BigPeltch <notifications@github.com>:

> I downloaded, your sample (called Friscth.mp4) and attempted playing it on
> my HTPC, again, it started then deadlocked. Again, Kodi.log and
> Kodi.old.log:
>
> http://sprunge.us/jVOR
> http://sprunge.us/HcLU
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3925#issuecomment-75131296>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment] 2015-02-19 21:07
Btw. this was not a debuglog ... enable debugging please.

Can you make this:
15:31:12 T:140563564508928  NOTICE: Universal - An Addons Toolkit:
-watchhistory- -Loading sqlite3 as DB engine version: 3.8.8.2
15:31:12 T:140563564508928  NOTICE: Universal - An Addons Toolkit: -
watchhistory - -Auto Cleanup Start
15:31:12 T:140563564508928  NOTICE: Universal - An Addons Toolkit:
-watchhistory- -DELETE FROM watch_history WHERE lastwatched < '2015-01-30'
15:31:12 T:140563564508928  NOTICE: Universal - An Addons Toolkit: -
watchhistory - -Auto Cleanup End

go away, please?

2015-02-19 22:05 GMT+01:00 Peter Frühberger <peter.fruehberger@gmail.com>:

> Video -> Acceleration: Decoding-Method: Software
>
> please
>
> 2015-02-19 21:39 GMT+01:00 BigPeltch <notifications@github.com>:
>
>> I downloaded, your sample (called Friscth.mp4) and attempted playing it
>> on my HTPC, again, it started then deadlocked. Again, Kodi.log and
>> Kodi.old.log:
>>
>> http://sprunge.us/jVOR
>> http://sprunge.us/HcLU
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpenELEC/OpenELEC.tv/issues/3925#issuecomment-75131296>
>> .
>>
>
>
>
> --
>                    Key-ID:     0x1A995A9B
>                    keyserver: pgp.mit.edu
> ==============================================================
> Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by BigPeltch** [comment] 2015-02-19 23:26
I sure can turn debugging on. Do you want me to enable all the options under debugging? Sorry if I am slow, I am new at this and learning tons. I don't know if I can make this history thing go away as I don't know what it is. If I can't I will redo a clean install without adding repositories nor add-ons.

Again I appreciate the help. I might only be able to get you those log files tomorrow.

**Comment by fritsch** [comment] 2015-02-20 07:33
No need to turn on component logging, just a normal debuglog.

I am not sitting here waiting -> your bug, your logfiles :-)

**Comment by mrdominuzq** [comment] 2015-03-31 18:50
@BigPeltch Any news on those logfiles :)? or has the problem gone away ?

**Comment by chewitt** [comment] 2015-07-22 13:27
closing due to lack of user response

**Closed by chewitt** 2015-07-22 13:27 UTC

**Comment by BigPeltch** [comment] 2015-07-22 14:37
I gave up on it and when the Ubuntu way. Sorry for not closing it myself.
