### ISSUE TITLE
Geniatech HDStar DVB-S2 problems

### ISSUE THREAD

**Issue by laptopu** [OpenELEC/OpenELEC.tv#4195] opened 2015-06-14 19:16 UTC
Unexpected behaviour with this receiver means many transponders are not recognised correctly and appear significantly out of the expected frequency.

Here is a log: http://justpaste.it/l5xd

If I scan say 12207V it comes up with the channels on transponder 11343V.

Although I haven't been through things for 100% certain, it seems to be mainly vertically polarised channels in the 'high' band on a universal LNB.

I have posted more info on this thread: http://forum.kodi.tv/showthread.php?tid=227135 but this is my overall summary here.  Others have reported problems with this hardware on the Outernet project site at https://discuss.outernet.is/t/arch-arm-orx-issue-installing-tvheadend/1076/2 and at Openelec http://openelec.tv/forum/83-dvb-s-s2-support/71717-geniatech-hd-star-dvb-s2-usb-raspberry-pi-openelec.

Thanks

**Comment by chewitt** [comment] 2015-12-27 07:05
I'm closing this ticket down because there's no clear guidance on what needs to be fixed. If you can point to a patch or version update that resolves the problem we'll apply it - if not please wait for 6.0.1 to be released then if the issue is still present start a forum thread (this is not a help forum) or perhaps try a milhouse Jarvis build that has newer kernel. Thanks.

**Closed by chewitt** 2015-12-27 07:05 UTC

**Comment by glaubermmferreira** [comment] 2016-04-24 20:08
This seems to be a general linux kernel issue (happens in OpenELEC, Raspibian, et cetera)
But with [this patch](http://outernet-project.github.io/orx-install/misc/geniatech_hdstar_modules.patch) provided by the Outernet Project and the appropriate binary kernel modules, tunning and scanning works fine.

PS: Tested on Raspibian, because I have no idea how to recompile the kenel for OpenElec.

**Comment by jaarsa** [comment] 2016-07-18 23:22
Any news on this matter?

I see that the patch is dated 2015, and latest fw for OE is 3.years old. This patch is reported to fix the issue with V.3 hardware.

One of the main problems are that there are no way to differentiate between v2 and v3.
http://discuss.outernet.is/t/new-raspbian-images-available-now-with-hdstar-support/1194

**Comment by jaarsa** [comment] 2016-07-21 12:26
Patch tested and working with copiled version of LibreElec 8.0 and TvHeadend 4.2.

Have also compiled latest version of OpenElec 8.0, but couldn´t make a compiled version of TvHeadend 4.2 to test with. TvHeadend 4.0 don´t work with OpenElec 8.0.

**Comment by CvH** [comment] 2016-07-21 13:37
@jaarsa could you link to the patch that is working (not to the board)?

**Comment by jaarsa** [comment] 2016-07-21 13:49
The patch is already inluded by @glaubermmferreira.

**Comment by jaarsa** [comment] 2016-07-23 22:17
Patch and compiled version of OE can be found here.
http://openelec.tv/forum/83-dvb-s-s2-support/82235-oe-6-95-3-with-geniatech-hdstar-v3-patch

**Comment by scropion86** [comment] 2017-09-06 07:56
@CvH @chewitt 

can you look at the below links and see if this is usable patch , as i still not able to use the card with LE
by kszaq latest [8.1.6] LibreELEC 8.2 for S905/S905X , i already posted the same on the forum [here is the link ](https://forum.libreelec.tv/thread/9796-amlogic-s905x-geniatech-mygica-hdstar-dvb-s2-v3-issue/)

[https://bitbucket.org/updatelee/v4l-updatelee/commits/55c63982a513c93bdd42034f3353395c3cc4b4f8?at=master](https://bitbucket.org/updatelee/v4l-updatelee/commits/55c63982a513c93bdd42034f3353395c3cc4b4f8?at=master)

[https://bitbucket.org/updatelee/v4l-updatelee](https://bitbucket.org/updatelee/v4l-updatelee)

**Comment by laptopu** [comment] 2018-01-03 21:23
I ended up throwing this receiver out, not well supported project and anyone who wants a media centre with satellite functionality I'd say buy a dedicated box made and sold with these features otherwise it's probably not good news sorry.
