### ISSUE TITLE
Scattered OSD, low & jerky video performance, false-colored & displaced screenshots with OE 5.0.7 / 5.0.8 on Cubox-i4Pro

### ISSUE THREAD

**Issue by projectb-temp** [OpenELEC/OpenELEC.tv#4067] opened 2015-04-04 12:09 UTC
OpenELEC 5.0.5 / 5.0.8 on SolidRun Cubox-i4Pro.

After updating from 5.0.5 to 5.0.7 (and later to 5.0.8) the video playback performance, screenshots and video overlays have changed.

Before udpate:
- Videos with 50fps play at 50fps, overall smooth video playback
- Debug text displays around 60fps
- Movie overlays (Info or Player controls) in confluence skin have smooth transitions
- Screenshots via SSH work fine and produce correct images

After update:
- Videos with 50fps play at an average rate of 40fps, noticable jerky video playback
- Debug text displays around 30fps
- Movie overlays (Info or Player controls) in confluence skin have scattered, rough transitions
- Screenshots via SSH work but produce false-colored and displaced images

After reverting back to 5.0.5:
- Everything works smoothly as it did before.

Logfile after update to OE 5.0.8: http://sprunge.us/DbQM

Movie playback screenshot taken with 5.0.5: http://fs1.directupload.net/images/150403/ww83zzai.png
Closeup of 5.0.5 screen taken with camera: http://fs1.directupload.net/images/150403/jvc9xfkj.jpg

Movie playback screenshot taken with 5.0.8: http://fs2.directupload.net/images/150403/fz6tcxfi.png
Closeup of 5.0.8 screen taken with camera: http://fs2.directupload.net/images/150403/ti4wwwwv.jpg

**Comment by fritsch** [comment] 2015-04-04 12:20
codec screen is _no_ benchmark. The cubox is far too slow to play 50 fps videos in general, no matter if you run 5.0.6 or 5.0.8. Since 5.0.8 a rendering rewrite has been integrated, so in general you can play a whole lot more content than before.

The main disadvantage here is, that whenever you display "debug info" or open the "codec info" the old render path will be used and fps will totally go nuts.

**Comment by fritsch** [comment] 2015-04-04 12:25
More information on current cubox nightmare: http://forum.kodi.tv/showthread.php?tid=211289

I am currently uploading a build for you, that makes the menu speed (while playing something" configurable, won't help the debug screen though.

**Comment by fritsch** [comment] 2015-04-04 12:29
And something else: That work was pushed into OpenELEC 5.0.x without my ack ...

**Comment by projectb-temp** [comment] 2015-04-04 12:32
Thanks for your support!

It seems if I turn on "set TV framerate to match movie framerate" the performance gets better and more stable with a smoother playback.

When changing the rendering mode from "hardware" to "software" the OSD looks as normal but the video performance is way too jerky.

**Comment by fritsch** [comment] 2015-04-04 12:38
Jep. As long as you keep the osd closed it should work quite nice ... still
uploading your test build. Please also check if menu's animation are back
to normal.

2015-04-04 14:32 GMT+02:00 projectb-temp <notifications@github.com>:

> Thanks for your support!
>
> It seems if I turn on "set TV framerate to match movie framerate" the
> performance gets better and more stable with a smoother playback.
>
> When changing the rendering mode from "hardware" to "software" the OSD
> looks as normal but the video performance is way too jerky.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4067#issuecomment-89560005>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by projectb-temp** [comment] 2015-04-04 13:04
OK. Just let me know when the build is ready and what should be my next steps/settings/etc.

**Comment by fritsch** [comment] 2015-04-04 14:05
Basically, only check the menu animations (if they are fine again) and second, please try a screenshot without debug screen and without menu visible. Then post a kodi.log and also dmesg | pastebinit please.

I am away for easter - upload needs ~60  minutes (will be here: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-5.0.8-revert1.tar ) <- wait at least 60 minutes, please and test extract it.

**Comment by projectb-temp** [comment] 2015-04-04 14:12
Thanks for your build.
I guess the package can be treated like a manual update (through the Update share) or do I have to re-flash the complete SD card?

I hope you have some quiet easter holidays and will report back after testing.

**Comment by fritsch** [comment] 2015-04-04 14:16
Nope - manual update is fine. If we can solve the "menu issues" and improve a bit when the "controls" (e.g. after pressing return) are in front - that would be nice.

Without that work, no live tv playback is possible, therefore I'd like to keep it (after it was pushed now anyways).

**Comment by fritsch** [comment] 2015-04-04 14:39
You can download now. In Video -> Acceleration you will find a new menu setting to reduce gui rendering when video is playing, keep that on 12 and later try also 24 (0 turns that feature off).

**Comment by fritsch** [comment] 2015-04-04 15:50
Ah, you have a very old boot config (uEnv.txt). It should look like:
boot=/dev/mmcblk0p1 disk=/dev/mmcblk0p2 quiet
video=mxcfb0:dev=hdmi,1920x1080M@60,if=RGB24,bpp=32 dmfc=3 consoleblank=0

Remount /flash rw and change the bpp to 16 and add the consoleblank=0 please

Then let's summarize again.

I am not against reverting everything. Problem we have:
- without that code the cubox will never play any live tv content, won't be
able to do 1080i50 deinterlacing
- things like debug on screen / codec info won't run any faster
- menu speeds while playing can be "workarounded" with the patch I
introduced in your build

Please revisit the screenshot, when you have changed your uEnv.txt
accordingly

2015-04-04 17:37 GMT+02:00 projectb-temp <notifications@github.com>:

> So here's my feedback:
> Screenshot: http://fs2.directupload.net/images/150404/7bqhxify.png
> Kodi.log: http://sprunge.us/ZiMc
> dmesg: http://sprunge.us/jDHi
>
> Settings:
>
>    - Match TV framerate to movie framerate at start/stop is active with 2
>    seconds delay
>
> When navigation through the menu without playing a movie it seems a bit
> slower and gluey
> When opening a menu while playing a movie (OSD) it seems to be farily
> fluid with glitches, hickups every now and then.
> When returning to main menu while playing the movie in the background and
> performing tasks in the main menu (navigating through main options, viewing
> movie database) its gluey as hell.
> The scattered OSD and the false-colored screenshots still occur.
> When setting the refresh rate to 24fps everything seems to be a bit
> smoother but still way to gluey.
>
> If there's anything I can test, please feel free to ask for it.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4067#issuecomment-89599801>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment] 2015-04-06 12:50
Ah I see you convenced github of not being a robot :-) I can reproduce the screenshot issue. But time ends again tomorrow. If you find time, check the SetupScreenshot implementation for IMX, please

**Comment by sraue** [comment] 2015-04-06 17:52
please test http://snapshots.openelec.tv/test/OpenELEC-imx6.arm-devel-20150406191913-r20184-ge3ddf83.tar

**Comment by projectb-temp** [comment] 2015-04-07 09:01
Hi you two,
Yes, I'm still human - and I convinced github of being so, too ;)

I did some testing with fritsch during the weekend and I'll just want to summarize them from my side:
Test using 5.0.5:
The menu handling is definitely more fluent and responsive than in 5.0.8 - this includes the situation when playing back a video, too.

When playing the 50fps progressive movie in background with the main menu shown the performance is lower than in 5.0.8. The movie is played back a lot chopier and even gets distorted some times. Video "stalling" when switching from fullscreen playback to background playback (with the main menu on top of the movie) is noticable but seems to be a bit less than with 5.0.8.

When stopping movie playback and returning to the (main) menu using 5.0.5 the menu is fluent and swift right after the movie has stopped - whereas with 5.0.8 it takes some time to get fairly fluent again (1-2 mins). But the menu in 5.0.8 never reaches the swiftness and performance it has in 5.0.5 in any situation.

I will test both of your builds by today and report back.

**Comment by fritsch** [comment] 2015-04-07 11:12
I see different results. With the newest image, I can even watch 1080i50 samples with 50 fps, when having the Limit GUI updates when playing video render set to 12 fps (the new setting), this even with the codec screen enabled.

I will revisit 720p50 and see. This file here: http://solidrun.maltegrosse.de/~fritsch/720p50_h264.mp4 does also produce those issues?

**Comment by projectb-temp** [comment] 2015-04-07 11:36
Maybe I was not clear enough:
- Performance of 5.0.5 when having the main menu in foreground while playing a video in background: Video (1280x720p50 / audio: 5.1 AC3 @ 48KHz) performance is very choppy, even distorts (chunks up) the video.

- Performance of 5.0.8 (OpenELEC-imx6.arm-5.0.8-revert1.tar) when having the main menu in foreground while playing a video in background: Video (1280x720p50 / audio: 5.1 AC3 @ 48KHz) performance is quite well but still noticeably lower than in fullscreen mode.

I didn't try 1080i50 in background but I will do so with the test files you supplied in the late evening. After doing this I can also give you an answer regarding the screenshot issue.

So by today evening I hopefully can test:
- Settings: Audio passthru disabled / Sync Playback to Display active [Video Clock, resample Audio] / Limit GUI updates when playing video render [12 fps]
- Video playback performance in background and/or with OSD/codec info activated
- Stalling of video playback when switching from fullscreen to background display
- Screenshot issue
- Testing with both interlaced & progressive test files from your account so we talk the same here

If there's anything I missed feel free to add it.

**Comment by fritsch** [comment] 2015-04-07 11:38
@projectb-temp thx much - that's all of it. Please use the latest image sraue posted.

**Comment by jamesdm** [comment] 2015-04-07 12:51
Guy I have a similar problem with the menues when the video is running I use thr sraue build and the problem persist.

**Comment by fritsch** [comment] 2015-04-07 13:39
Just, press "stop" and fine ... the cubox has not enough power to do both in all cases.

**Comment by projectb-temp** [comment] 2015-04-07 18:11
OK I'm done with the progressive testing (1080p50_h264.mkv, 720p50_h264.mp4).
Debug Log: http://sprunge.us/jHTT
dmesg: http://sprunge.us/CDGc
Screenshot (taken from 1080p50_h264.mkv): http://fs2.directupload.net/images/150407/o76tkb2n.png

Video performance is quite good and fluid. Even when displaying OSD (Info screen, codec info or player controls). When displaying codec info together with another OSD (info screen or player controls) the video seems to have some microstutter but just very few and irregulary.

Video performance when playing in background is as bad as before, including some stalling and video/audio displacement and "fast forwarding" when exiting background playing. I think the cubox is just at it's performance end here.

Menu performance is very good after booting and was also well while playing a movie (responsivness of movie info and player controls). Performance after stopping a movie is better than before. Nearly no gluey effects right after stopping playback. It seems almost as responsive as after booting.

Screenshots look good, even though the OSD information is missing (as stated by @fritsch).

Will test interlaced videos by now.

**Comment by fritsch** [comment] 2015-04-07 18:14
For Gui rendering another fix was added - I will do a new build now. Let's see how you like it

**Comment by projectb-temp** [comment] 2015-04-07 18:44
Done with the interlaced testing (1080i50_h264.ts, 1080i50_h264_mbaff.mp4).
Debug Log: http://sprunge.us/GQYN
dmesg: http://sprunge.us/DfNB

Video performance of 1080i50_h264.ts is quite good and fluid, even when displaying OSD (Info screen, codec info or player controls). When displaying codec info together with another OSD (info screen or player controls) the video seems to have some microstutter. De-interlacing works ok for both methods. But trying to skip backwards is very balky and almost not functional (it skips backward a bit but needs so much time to render the output that you're almost at the position before starting the skipping).

Video performance of 1080i50_h264_mbaff.mp4 is quite good and fluid, even when displaying OSD (Info screen). When displaying codec info, player controls or a combination the video has permanent periodic microstutter. De-interlacing works not very well in both methods (worst screenshot of a very demanding scene: http://fs1.directupload.net/images/150407/fkjzgdft.png). Skipping backwards seems to work good with this movie.

Video performance when playing in background is quite good with almost no stalling and just a bit less performance. Even when switching back to fullscreen it plays quite smooth.

Menu performance right after stopping a movie is as good as with progressive movies.

Beside the fact that de-interlacing is not as good, screenshots look good.
@fritsch : Great! Let's see if I can test this build tomorrow in the evening.

**Comment by fritsch** [comment] 2015-04-07 19:11
Which deinterlacing method did you test? IMX-FAST or Double rate? Double Rate is very demanding - I use IMX-FAST, which is also done when in AUTO. 

I sent the build via mail, cause over the WE my dropbox was DDOSed and it was closed down (more than 20 gb traffic) :-(

**Comment by projectb-temp** [comment] 2015-04-07 19:27
As written above I tested with both methods and both did not produce very good results when watching the mp4 video.

OK, I'll hopefully be able to test it by tomorrow.

**Comment by fritsch** [comment] 2015-04-07 19:30
Double-Rate is "the piece of juice" ontop. I am not that sure, we ever get that working - but never say never ...

**Comment by projectb-temp** [comment] 2015-04-08 16:21
OK I'm done with the progressive testing (1080p50_h264.mkv, 720p50_h264.mp4) on @fritsch new build.

Debug Log: http://sprunge.us/AVbS
dmesg: http://sprunge.us/IWHa
Screenshot (taken from 720p50_h264.mp4): http://fs2.directupload.net/images/150408/yyc7c52b.png

Video performance is as good as before. It gets worse when enabling codec info and additionally opening the player controls. If then another window is opened additionally (e.g. opening the audio settings through the player controls) the performance drops further.

Video performance when playing in background seems as bad/"good" as before. But the navigating through the main menu seems to have less impact on the playback performance. Demanding menu options (e. g. displaying the weather) seem to have more impact on the performance than just displaying the latest added music.There's still slight stalling when entering backround playback and "fast forwarding" when leaving it.

Menu performance right after booting and after finishing a movie is as good as before.

One more thing I noticed: After the movie stopped and I was back in main menu I took another screenshot. This time the screenshot was just 7kB in size and completely black: http://fs1.directupload.net/images/150408/mm6fsdmb.png
This issue continues for every screenshot I took after movie playback ended.

Will test interlaced videos now.

**Comment by fritsch** [comment] 2015-04-08 16:41
@projectb-temp Thanks for that report. Btw. Can you check the "Skip" Counter on the codec screen? It does not really increase, right?

**Comment by projectb-temp** [comment] 2015-04-08 17:03
Done with the interlaced testing (1080i50_h264.ts, 1080i50_h264_mbaff.mp4).
Debug Log: http://sprunge.us/HcFP
dmesg (looks very strange this time!): http://sprunge.us/eKFg

Video performance of 1080i50_h264.ts is as good as before with degrading perfromance when adding more on screen elements. De-interlacing seems t have slight problems using both methods in demanding scenes: http://fs2.directupload.net/images/150408/4mmwrper.png

What I noticed when switching to double-rate: When starting the movie with double-rate enabled there is a very noticable discrepancy between audio and video. When using the "rewind to start" function audio and video are in sync again. When switching back to normal de-interlacing this effect cannot be seen. Skipping backwards is still not possible (as we discussed, @fritsch).

Video performance and backwards skipping of 1080i50_h264_mbaff.mp4 is as good as before. De-interlacing works better now: http://fs2.directupload.net/images/150408/af6eckj7.png
It seems OSD elements are rendered into the screenshots now: http://fs2.directupload.net/images/150408/ou7yxvvu.png

Also, screenshots of the main menu, taken after stopping the movie, don't result in black images but work as they should.

Video performance when playing in background is quite good with almost no stalling and just a bit less performance. Even when switching back to fullscreen it plays quite smooth.

Menu performance right after stopping a movie is as good as with progressive movies.

The "skip" counter in the codec screen doesn't move if just playing the video or navigating through the player controls. It increases by 1 when manually triggering a "skip" via the remote control. It also increases noticebly when entering and exiting backround playback of a movie (around 6-9 skips per action if I remember correctly).

**Comment by foresto** [comment] 2015-04-10 09:03
The switch from 5.0.6 to 5.0.7 introduced at least one problem for my CuBox-i, too: When playing h.264 content and I press "i" to get the video information overlay, the background of the overlay is now a very rough dithering pattern instead of the usual smooth gradient. Same problem in 5.0.8.

Is this another symptom of what you folks are already discussing? If so, I won't waste my time gathering logs, etc.

**Comment by fritsch** [comment] 2015-04-10 09:16
@foresto Your uEnv.txt is from an old installation. Mount /flash rw and change the color depth to 32.

**Comment by jamesdm** [comment] 2015-04-12 00:23
fritsch I test that build and the osd problem is gone but just to say that the transition between the info or the controls in the osd is very slow but the video plays allways normal.

**Comment by fritsch** [comment] 2015-04-12 06:49
The gui is limited to 12 fps, when video is playing. You can tune that value in Video -> Acceleration -> Limit Gui fps ... With 24p playback 24 fps should be working, also. With 50p fps, 10 is max - therefore I chose 10 - which is btw. also the default on the Raspberry PI 2

**Comment by foresto** [comment] 2015-04-13 08:42
@fritsch, thanks for the tip. I installed with OpenELEC 5.0, which used bpp=16, and the minor upgrades since then apparently didn't bother to update it. Manually setting bpp=32 fixed the dithered gradient problem.

I noticed some more problems with 5.0.7 and 5.0.8, which might have more to do with this bug report: 

- 3D side-by-side content now plays at a low frame rate, with the right eye completely blacked out.
- Some 2D videos are being rendered with a narrow white bar along the right edge of the frame.

Reverting to 5.0.6 fixes both problems. If these are not known issues, let me know, and I'll get some logs.

I installed the build that you linked in your last reply to me, but rebooting left my display with a black screen. I wasn't watching the boot sequence and I'm out of time tonight, so I don't know if it was the OS or just Kodi that failed. I'll probably have time for more testing in a few days.

**Comment by fritsch** [comment] 2015-04-13 08:53
Try with that one, better: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-5.0.8-sysfsartifacts.tar

**Comment by foresto** [comment] 2015-04-15 06:37
Both problems are in that one as well.
Regarding the 3D issue: When I put my display in 2D mode, I see that Kodi is rendering both sides of the 3D side-by-side content squished into the left eye space, while the right eye space is left black.

**Comment by fritsch** [comment] 2015-04-15 10:49
3D Modes nobody has tested at all. So if you need that functionality you
need to downgrade to 5.0.6

I am interested in that 2D artifact, please make a picture of the issue and
if possible provide a sample that produces it.

Btw. the code that landed in 5.0.7 / 5.0.8 was never meant to land there,
but thanks for reporting those bugs.

2015-04-15 8:37 GMT+02:00 Forest <notifications@github.com>:

> Both problems are in that one as well.
> Regarding the 3D issue: When I put my display in 2D mode, I see that Kodi
> is rendering both sides of the 3D side-by-side content squished into the
> left eye space, while the right eye space is left black.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4067#issuecomment-93219100>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by jamesdm** [comment] 2015-04-20 21:52
Quetion: When I have the video playing and quit the fullscreen mode the audio is Ok but the video is like "slow" like is skipping frames.

**Comment by fritsch** [comment] 2015-04-21 06:32
Yes - box is too slow for doing both. Menu rendering and video playback. Try this: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-devel-20150420112830-r20197-gd420281.tar

it slows down menu rendering when video playback is active

**Comment by projectb-temp** [comment] 2015-04-21 07:41
Hey fritsch, thanks for this new build! Is this finally an Isengard build?
If so I might be able to test within the next few days.

**Comment by fritsch** [comment] 2015-04-21 07:58
Nope - final stuff that I plan for Helix.  Perhaps I will include:
https://github.com/xbmc/xbmc/pull/6996

I am stuck with my dropping implementation (lack of time) ...

2015-04-21 9:41 GMT+02:00 Bernd <notifications@github.com>:

> Hey fritsch, thanks for this new build! Is this finally an Isengard build?
> If so I might be able to test within the next few days.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4067#issuecomment-94673301>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by projectb-temp** [comment] 2015-04-21 08:01
Hi Peter,

wem sagst Du das mit der Zeit...

Ich hab ab nächster Woche 3 Wochen Urlaub - vielleicht komme ich da zu ein
wenig mehr Testen, wenn gewünscht.

Wie war die Messe?

Mittlerweile funktioniert mein shutdown script für die Box. :)
Ich hab noch ein paar Fragen bezüglich github - vielleicht komme ich noch
einmal auf Dich zu.

Besten Gruß
Bernd

**Comment by fritsch** [comment] 2015-04-21 08:06
Here is code that I am currently working on: https://github.com/fritsch/xbmc/commits/imx-fixes <- see the dropping code

**Comment by jamesdm** [comment] 2015-04-22 21:06
fritsch the video is still slow when I exit the fullscreen with the video running.

**Comment by fritsch** [comment] 2015-04-23 06:22
And that won't change. This is the limit of the cubox. If you want it
faster -> buy new hardware.

2015-04-22 23:06 GMT+02:00 jamesdm <notifications@github.com>:

> fritsch the video is still slow when I exit the fullscreen with the video
> running.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4067#issuecomment-95336319>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by stefansaraev** [comment] 2015-04-26 18:06
@sraue what we are doing here ?

**Comment by foresto** [comment] 2015-04-26 19:00
For the record: @fritsch has a build that fixes the 2D artifact that I mentioned, as well as another one that I hadn't yet reported on the tracker.

**Comment by stefansaraev** [comment] 2015-04-26 19:03
yea, I guess he reverted something.

**Comment by fritsch** [comment] 2015-04-26 20:35
Nope - I fixed it and pushed it here:
https://github.com/fritsch/OpenELEC.tv/commits/imx-retries2

2015-04-26 21:03 GMT+02:00 Stefan Saraev <notifications@github.com>:

> yea, I guess he reverted something.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4067#issuecomment-96421031>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by chewitt** [comment] 2015-12-23 11:57
@fritsch @projectb-temp - I am going through old tickets to get updates or close them out. Is this still an issue in OE 6.0.0? - or is there anything to patch or merge?

**Comment by fritsch** [comment] 2015-12-23 17:49
All code that was written in is kodi master ... for actively developed imx distributions see osmc / xbian

**Comment by projectb-temp** [comment] 2015-12-23 19:57
So I think this Ticket can be closed from my side as it wont't get any better with CuBox.
Thank you a lot for your Work, fritsch!

**Comment by chewitt** [comment] 2015-12-23 20:07
thanks for the update, closing.

**Closed by chewitt** 2015-12-23 20:07 UTC
Labels: bug, regression
