### ISSUE TITLE
OE 5.0.6 Cubox transposing bottom row of pixels to top of video

### ISSUE THREAD

**Issue by bconway** [OpenELEC/OpenELEC.tv#4037] opened 2015-03-24 01:05 UTC
On 5.0.6 on a CuBox i2-eX.

Test file: https://dl.dropboxusercontent.com/u/31824887/sw-03-aac_dd20-extsub-cfr.mkv

Steps to repro:
1.) Watch the above file on any of the following (being fullscreen helps): VLC, Kodi OS X, OpenELEC RPi B 512.
2.) Watch the file again on OpenELEC Cubox.

The sections with Leia's bright white robe make it easy to see the effect of the bottom row(s) of pixels of the video appearing at the top. Screenshot showing the effect: http://dl.dropboxusercontent.com/u/31824887/screenshot000.png

Cross-post for discussion here: http://openelec.tv/forum/125-solidrun-cubox-i/76133-transposing-bottom-row-of-pixels-to-top-of-video

Thanks.

**Comment by lrusak** [comment] 2015-03-24 02:10
Please follow our guidelines for [contributing](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md)

**Comment by bconway** [comment] 2015-03-24 02:21
Which information is missing?

**Comment by amak79** [comment] 2015-03-24 03:07
This is a duplicate of issue #3781.

**Comment by fritsch** [comment] 2015-03-24 06:49
Won't be fixed. Cubox decoding and rendering was fully reworked for v15. If the issue still appears with: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-devel-20150322143813-r20133-g890c4cc.tar open a bug at trac.kodi.tv

**Closed by fritsch** 2015-03-24 06:49 UTC
Labels: imx6
