### ISSUE TITLE
Fully broken VDR in openelec 5.95.5

### ISSUE THREAD

**Issue by odc2** [OpenELEC/OpenELEC.tv#4351] opened 2015-10-02 12:00 UTC
I cant use VDR in any case i tried. It worked perfectly in 5.0.8. In 5.95.5 it simply cant start. Images are always x86_64.

How i used it in 5.0.8: http://freaktab.com/forum/advertisers-and-vendor-support-area/wetek/24582-tutorial-setting-up-vdr-on-openelec

How it look in 5.95.5:
When i scan for "VDR" i find 3 things:
1. VDR Configuration
2. VDR PVR Backend
3. VDR VNSI Client

I press install on VDR PVR Backend. It installes then all the 3 things (seems to be dependency now). After that i go to TV part and enable it. It tells me that the client is been disabled and opens a page where i can see that VNSI is turned off. I press enable.
After that TV is been enabled in settings. I go now to http://s5.postimg.org/jvmwz4u93/screenshot014.png
I press enter like on 5.0.8, but it never opens http://s5.postimg.org/638i3i3hj/screenshot015.png

I reboot the system. At reboot it every time tells me that VDR is been enabled and i have to enable it (same message like described above). I try again to open the VDR settings. It also never open.
Yes, there is the adapter detected fine:
/dev/dvb/adapter0

kodi log with enabled debuging: https://pastebin.mozilla.org/8848149

This bug can be reproduced on 3 fully different devices with different hardware. It can also be reproduced on a pc without DVB card.

**Comment by stefansaraev** [comment] 2015-10-02 12:23
this is not a bug. you are supposed to 1. open pvr client's settings 2. save 3. enable it.

**Comment by odc2** [comment] 2015-10-02 12:46
Thanks for the quick answer.
I went to the "VDR VNSI Client" (version 1.10.10) where you can Uninstall, Disable and Configure it. I choose the "Configure" on the top. It opens the page with "VDR Hostname or IP - 127.0.0.1" and so on. I didnt change anything and press OK. When i try to restart (disable, enable) i get message that it cant disable it because its been used by the VDR PVR Backend. I then disable and enable the VDR PVR Backend.
It should work now, right? It doesnt. I go again to "Client specific" and try to view the VDR settings. They didnt open as described above.

**Comment by vpeter4** [comment] 2015-10-02 18:19
Seems your VDR PVR Backend doesn't run. That's why you can't get VDR OSD. Configure that one first. And also check in SSH if process vdr.bin is running.
I need to reboot the box once to get OSD visible. Don't know why.

**Comment by fritsch** [comment] 2015-10-02 19:33
Unpacked the box, upgraded directly to 5.59.5, whiped my .kodi directory. Configured VDR, vnsi was installed ... just works ...

**Comment by fritsch** [comment] 2015-10-02 19:33
Will now fully remove .kodi again, reboot and try to configure it from scratch and see what will happen :-)

**Comment by fritsch** [comment] 2015-10-02 19:49
Rebooted, I wanted to install VDR, but VDR was automatically enabled and installed as was the "VDR Configuration" under programs. I directly went to this Programs -> VDR Configuration and started the channel scanner. That needed some time - a long time (found 507 channels). Then went to Live TV,  Wanted to enable it. I was told: No client addon installed. I went to vnisi clicked setting, navigated to the OK button, pressed it. Click on Enable, VNSI popped up and fetched EPG data ... I did not have to do anything at all (besides channels scanning). When I click on client specific I get this ugly menu, that I thx to channel scanner addon don't have to use anymore.

So - even with a fresh wetek box I cannot reproduce your issue. I am using DVB-C here.

If you would not believe me - I could upload every screenshot you'd like to have.

**Comment by odc2** [comment] 2015-10-03 18:28
@fritsch 
I dont have such a wetek ARM box that i could test the bug on it. As told in the first message i am using x86_64. I cant check if that makes some differente to ARM.
As vpeter4 told i am using the VDR OSD like i told in the first message:
http://s5.postimg.org/638i3i3hj/screenshot015.png

Is this VDR OSD working fine for you?

**Comment by fritsch** [comment] 2015-10-03 18:34
Yes - here a screenshot:
![osd](https://cloud.githubusercontent.com/assets/1089309/10264513/0fe19c86-6a0e-11e5-89a3-575df1ea4fac.png)

Btw. I use many clients that run OE and use my (though) remote VNSI server ...

**Comment by odc2** [comment] 2015-10-06 15:30
I got that working now. After tons and tons of tries. But it cant find any channel on the most free DVB-T device existing! It was working perfectly fine in 5.0.8. The RTL2832U.

How to get that OSD working.
How i get OSD opened:
1. Install openelec 5.95.5 and start it
2. install vdr backend. it installs then the other two vdr things.
3. Enable TV in settings and enable (again) the vnsi client.
4. Try to open OSD - it wont work.
5. Disable TV
6. reboot system
7. Go to VDR backend and inside its configuration go on the right to load the defaults. then press ok.
8. No go to VNSI client (Important: its still enabled from before reboot) and open configuration. press ok
9. Enable TV
10. Go to OSD settings.

**Comment by odc2** [comment] 2015-10-06 15:33
About the non working scan:
in 5.0.8 the percentage (X% transponders from scan) was much much slower on 5.0.8. Now on 5.95.5 the scan is finished in about 1 minute. On 5.0.8 it took about 10-15minutes to get 100% (and show in the meantime the channels that have been find).

**Comment by odc2** [comment] 2015-10-06 15:35
About the try to use "VDR Wirbelscan Control", the new VDR scanning service:
The scanning speed of "VDR Wirbelscan Control" is the same like in the VDR OSD (much faster then 5.0.8) and it also does not find any channel.

**Comment by odc2** [comment] 2015-10-06 15:40
When i go to System information and there to the "PVR service" it is showing me:

Disksize: -4503442601017344 B of 146,2 GB available.

Its a typical 160GB HDD. This is also a "bug".

**Comment by odc2** [comment] 2015-10-08 19:30
I tried w_scan. w_scan is finding channels.

**Comment by odc2** [comment] 2015-10-10 17:32
I made now DVB-S(2) tests (on a fully other x86_64 system).
After i enabled VDR with the 10-steps way i described above, i ran a scan. It scanned and i could see new channels found. I tought it were working now ... but shortly before end of the scan VDR crashed/restarted. I could see the message pop-up, that VDR service is been closed and shortly after enabled again.
After i reboot the system there was some channels and i could tune into them.
After that i tried to delete some channels in VDR OSD menu. After some channels were deleted, i was not able to tune into channels that was working before. I made a reboot. I was still not able to tune into those channels.

Also on that machine i had this "Disksize: -xxxxxxxxxxxx of xx GB available" bug.

**Comment by odc2** [comment] 2015-10-25 22:16
I am compiling at the moment the latest version and will report once again. Lets hope some magic fixed the problems. I didnt get any more answers from the developers.

**Comment by odc2** [comment] 2015-10-28 10:01
I made Tests on the DVB-S device. Its still broken and unusable.
What happened now:
I made a fresh installation, enabled VDR with the described 10 steps above and ran then a scan. The scan ran trough and VDR reported that it had find over 1100 chanels. I checked the VDR channel list itself. They was there inside.
TV section was enabled. So i went there and checked the amount of the channels. This was 899. Not more.
I reboot then the system. After that VDR was fully broken. It didnt start any more. I tried part of the 10 steps above, but it was not possible to start VDR(OSD) and/or TV-section inside openelec any more.
So the system was once again fully unusable.

Here are the logfiles:
Scan: http://xbmclogs.com/pccxajfgv
After reboot without TV any more available and not beeing able to enable: http://xbmclogs.com/paabhxzly

**Comment by eldingraho** [comment] 2015-10-28 11:07
go to system --> TV --> Guide and clear data 
or
SYSTEM --> TV --> General and clear data

This should fix the error you get:
20:01:48 T:139690095228672   ERROR: SQL: Abort due to constraint violation
                                            Query: INSERT INTO channels (iUniqueId, bIsRadio, bIsHidden, bIsUserSetIcon, bIsUserSetName, bIsLocked, sIconPath, sChannelName, bIsVirtual, bEPGEnabled, sEPGScraper, iLastWatched, iClientId, idEpg) VALUES (58216364, 1, 0, 0, 0, 0, '', 'Inselradio', 0, 1, 'client', 0, 828, -1)

**Comment by odc2** [comment] 2015-11-03 09:48
I have fully deleted this broken system and installed 5.0.8.
@eldingraho 
This is not a solution. The error that happened should not happen. Clearing data is not any kind of solution to the bug.

**Comment by odc2** [comment] 2015-11-03 11:54
Because @fritsch wrote here https://github.com/OpenELEC/OpenELEC.tv/issues/4417 "sorry it seems OpenELEC is not made for you - go and use something else, but stop going on the nerves of people. " - with other words - you are too stupid to use the software if you find any bugs, and blocked me of reporting, i have to write here.

From irc #openelec room:
<vpeter> odc2: Because I assume it doesn't. Go in to addons, find vdr addon, go into configure, and select ok at the bootom. Then reboot.

To report a fully debugging log so that @fritsch cant tell again that i am too stupid to use the software i made a hard reset and first enabled the debigging. After that i followed exactly what @vpeter4 (i think he have the name vpeter in irc) told me.

<odc2> http://xbmclogs.com/p3rmdcp1w
<odc2> the logfile is: fully new installation of openelec 6.0 x86_64 nvidia legacy (hard reset), bootup, enable debugging, installing VDR, pressing ok in vdr configuration -> still not working. reboot(as @vpeter4 told).

<odc2> second logfile: http://xbmclogs.com/pntmj9jiy
<odc2> this is the logfile after reboot. VDR still not working (@vp.

By the way in https://github.com/OpenELEC/OpenELEC.tv/issues/4417 @fritsch told me, that

**Comment by fritsch** [comment] 2015-11-03 12:25
Can you cite, where I called you stupid?

**Comment by fritsch** [comment] 2015-11-03 12:43
And now I will tell it again for you: You still are not able to post what the contributing link wants from you. You post damn kodi logs while your issue is vdr - which is not logging into kodi's log ...

Here, for you again: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

And as you gave as now the answer in public, yes it seems you have issues reading and supplying logfiles that are needed - if _you_ call this stupid, then yes - this is stupid and wastes people's time.

**Comment by the-dreamer** [comment] 2015-11-05 13:49
@eldingraho look: https://github.com/OpenELEC/OpenELEC.tv/issues/4188

its already reported here and also upstream ... because of missed timers due this bug (rtc wakeup is only setted when pvr is running) my current workaround is to delete the Epg* and TV* Database in autostart.sh. I am not sure if this will always help because of no Long-term experiences currently.

**Comment by 3ddd** [comment] 2015-11-15 20:45
I had also to enable VDR the way described here: https://github.com/OpenELEC/OpenELEC.tv/issues/4351#issuecomment-145901660
My other attempts before reading this Post failed all.

**Comment by odc2** [comment] 2015-11-16 10:27
I gived VDR on OpenELEC up. There is an other solution:
Short what was all the time reproducible broken in VDR for me:
- Enable VDR have to be done with a workaround (Bug Nr1)
- VDR breaks many times when scanning for channels on DVB-S and can only be enabled again, when removing the databases like described from @eldingraho above. (Bug Nr2)
- VDR finally, when the channels was clickable and VNSI was working, dont play some channels. The stream just didnt start. It was reproducible all the time. Some channels NEVER played. This was all free TV channels. They was all working with same Card and other software (no VDR+Kodi). This problem is there on 5.0.8 and 6.0.0. When you press on a channel that is been scanned about 5minutes ago, nothing start playing. No typical kodi-sound appear. Just nothing happens when you press that channel. (Bug Nr3)
There are still many other bugs i described but noone seems to care.

Solution: Dont install this VDR crap. Install TVHeadend. Its way more complicated to configure and you need a external computer to configure it over http-webpage, BUT its working! You can enable it, you can scan with it and you can play back every channel. AND you can listen to DVB-S radio with it (also not possible with VDR).

**Comment by the-dreamer** [comment] 2015-11-16 13:14
We all already know that you have big problems to get vdr running. There are thousands of perfectly running vdr installations out there. But you have big unsolvable problems. Find the track. 

But at all you missed the most important point: OpenElecs developer are mostly not developers of Kodi, VDR or all the other software which are included in OE.
OpenElec is a distribution. If there are bugs in Kodi. Go to kodi.tv. If you have any problem with VDR go to vdr-portal.de and so on. 

Btw: tvheadend sounds good on paper, maybe also usable for some people. But if you are using a sat dish you can spent lot of time of sorting the channels on the sometimes slow web interface. TVHeadend is maybe quite stable since one year. VDR is stable for much more years and therefore the backend of choice.

**Comment by chewitt** [comment] 2015-12-27 06:13
I'm closing this due to lack of specific evidence of a problem. If you still have issues please create a forum thread for discussion - this is not a user-help forum. Thanks.

**Closed by chewitt** 2015-12-27 06:13 UTC
