### ISSUE TITLE
3D movies in 2D not working anymore on Openelec 5.0

### ISSUE THREAD

**Issue by ozirissp** [OpenELEC/OpenELEC.tv#3725] opened 2014-12-28 23:02 UTC
The downscale to 2D of a 3D movie is not working with Openelec 5.0 final (tested on MKV file)

The feature was working correctly with XBMC Gotham and Openelec 4.2.1, I was able to switch in 2D , 3D movies, and it was good. It was keeping only one side of the 3D stereoscopic file.

Sadly, this feature is now broken in KODI Helix with final release of Openelec 5.0. :(

Now when we switch to 2D mode, the output show the full stream, with no 3D pre-processing, and keep the output untouched (the 2 images of stereoscopic, Side by Side or Top And Bottom, like a normal movie ...)

actual![sbs-3 d-to-3d-actual](https://cloud.githubusercontent.com/assets/7404696/5565244/e745efda-8eed-11e4-9304-10756d60fcf4.jpg)

expected ![sbs-3d-to-2d-expected](https://cloud.githubusercontent.com/assets/7404696/5565245/ecc013be-8eed-11e4-9ecf-e2ddc62132e0.jpg)

Thx for your hard work, I realy enjoy Openelec !

**Comment by ozirissp** [comment] 2015-01-03 21:21
@popcornmix 

I've got the same behavior with the flags ... And the second press of Watch as 2D solve the probleme ... (Thank you for the workaround)

The problem is the same with omxplayer acceleration off ... It doesn' work on the first press either ..

**Comment by anaconda** [comment] 2015-01-03 22:00
Just a note: it's not just the GUI misbehaving. I get the same behavior with a remote button mapped to `StereoModeToMono` (toggles monoscopic mode), two presses fix it.

**Comment by anaconda** [comment] 2015-01-06 15:29
@popcornmix mind taking a look at https://github.com/anaconda/xbmc/compare/popcornmix:newclock4...popcornmix/newclock4-fix-stereo2mono ?
This fixes it for me. However, that's still original code from elupus (PR 2848), so either I'm only curing the symptoms and the problem is somewhere else in a Pi specific code path, or this has never worked on any platform (this seems to be confirmed in https://github.com/OpenELEC/OpenELEC.tv/issues/3725#issuecomment-68249363 though...).
(Note that reverting your changes - https://github.com/popcornmix/xbmc/commit/92a53cb7dccc8e7f1719e15810d11ad85da956ec - to CGraphicContext doesn't fix it.)

**Comment by popcornmix** [comment] 2015-01-06 18:13
@anaconda certainly looks plausible. Have added it to newclock4 for further testing.

**Comment by ozirissp** [comment] 2015-01-10 23:53
@popcornmix 
I would be able to do it later this month, where can i find Milhouse build ?

**Comment by MilhouseVH** [comment] 2015-01-11 00:29
http://forum.kodi.tv/showthread.php?tid=211501

**Comment by chewitt** [comment] 2015-12-19 11:58
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.

**Closed by chewitt** 2015-12-19 11:58 UTC
