### ISSUE TITLE
Cannot set static IP without dynamic IP connection

### ISSUE THREAD

**Issue by miigotu** [OpenELEC/OpenELEC.tv#4099] opened 2015-04-18 01:25 UTC
I have DHCP disabled in my router, so initial connection from OE on rPi cannot succeed.

The only workaround is to first enable DHCP in my router, connect to the AP with OE settings addon, edit the connection with my static IP, disable DHCP in my router settings, and reconnect network in OE.

I should be able to specify IP, Gateway, and Netmask in order to connect for a new connection, not just edit an existing connection.

Also, I noticed this when swapping out my router for a new one which I preconfigured with the same setup as the old one. Of my 12 devices connecting over wireless, OE was the only device that failed to automatically connect to the new router (Same SSID and PW, different mac).

**Comment by chewitt** [comment] 2015-04-18 03:47
I do not support the idea of creating static connections from within the initial setup wizard; too many n00b users will take up the idea then complain about things not working that result from their own configuration mistakes. I do support the idea that you should be able to create a connection from scratch within the settings addon instead of editing a current one. Perhaps when you highlight/click on Ethernet or the SSID it should ask you whether to use DHCP (default) or configure static details? NB: Although I support this I am not the person to be fiddling with python code in the addon (if you want it to work, etc.).

**Comment by stefansaraev** [comment] 2015-04-18 09:42
duplicate of #4081
closing.

**Closed by stefansaraev** 2015-04-18 09:42 UTC

**Comment by stefansaraev** [comment] 2015-04-18 13:27
@chewitt

> I do not support the idea of creating static connections from within the initial setup wizard

to make it clear: this is already supported in wizard. but is broken in recent 5.0.x (connman crashing). now that's fixed in "next" stable.

**Comment by miigotu** [comment] 2015-04-18 21:32
@stefansaraev this is a different issue than #4081 
I cant even get to a menu to set the static IP because the connection hasn't been made yet. Currently you can only set a static IP if the connection is already existing and saved in connman. If DHCP is disabled in the router one cannot connect and save the connection (in order to go back and edit it with static ip) because it fails on the configuring stage and never gets saved as a valid connection.

**Comment by stefansaraev** [comment] 2015-04-18 22:24
> I cant even get to a menu to set the static IP because the connection hasn't been made yet

then you are talking about wifi ? because "edit" is possible for wired connections.

> If DHCP is disabled in the router one cannot connect and save the connection

we dont consider supporting your wifi edge-case.

**Comment by miigotu** [comment] 2015-04-19 00:42
Also, I just was doing some tests for an issue I was having and decided to use `create_sdcard` with Milhouse build `#418`

On initial boot, wifi is disabled so networks don't even show up. The only way is to either enable dhcp in my router and connect, edit the connection, and then turn off dhcp in the router, OR pull the sd and copy the old .cache/connman/wifi_*_managed_psk/settings onto the storage partition.

Shouldn't wifi be enabled by default if a wireless adapter is found? And I should be able to specify dhcp|manual just before|after entering th passphrase on the connect wizard and enter the static ip, both from first run wizard and plugin settings.

**Comment by stefansaraev** [comment] 2015-04-19 15:31
> On initial boot, wifi is disabled so networks don't even show up ..

> Shouldn't wifi be enabled by default if a wireless adapter is found?

indeed. that was broken. yes, it should be enabled. see #4101

setting dhcp/manual before entering the passphrase is not possible. nothing I can do about that.
