### ISSUE TITLE
E-450 Fusion-HTPC on generic build (master): flickering screen at odd freqencies (23.98, 29.97hz)

### ISSUE THREAD

**Issue by top-gun** [OpenELEC/OpenELEC.tv#2924] opened 2014-02-08 20:50 UTC
Hi,

when I use the Fusion-build 3.2.4, I can use all screen rates from 23.98hz up to 60hz without any issues. On the new generic builds, only 24hz, 25hz, 30hz, 60hz work fine.

The system is a Zotac AD-04 connected to a Samsung-TV via HDMI, no AV-receiver in between.

The issue does not only occur in a video, but also when I set the refresh rate for the whole GUI in settings->system->video-hw. 24hz, 30hz, 50hz and 60hz play perfectly fine, 23.98, 29.97hz flicker badly. This happens on all generic builds which I tried, both with 3.12- and 3.13-kernels.

The following logs were taken with a built I started this morning after "make clean". I enabled xbmc-debuglogging.

The HTPC was booted with a screen set to 24hz. then I changed from 24hz to 23.98, and it started to flicker. I did not acknowledge the new rate and it went back to 24hz. The logs were done immediately afterwards.

dmesg|pastebinit:
http://sprunge.us/cGiM

cat xbmc.log|pastebinit:
http://sprunge.us/EKIS

/usr/lib/xbmc/xbmc-xrandr|pastebinit:
http://sprunge.us/TXAJ

If I can supply anything else, I will gladly comply. These are the logs seo advised me to provide in the chat.

Regards,

Detlev

**Comment by mrdominuzq** [comment] 2015-04-14 18:40
is this fixed? a whole year :)

**Comment by hensing** [comment] 2015-05-02 20:40
Finally today I had the time to test it again with the latest version of OpenELEC:

All frequenzies but 25 Hz are working. With 25 Hz I still get the known up/down-flickering effect :(

**Comment by fritsch** [comment] 2015-05-03 06:37
25hz is 1080i50 and not done natively by the TV - it's nothing you would
want. If the TV announces 50i as 25hz, you have a big problem.

2015-05-02 22:40 GMT+02:00 Henning Dickten <notifications@github.com>:

> Finally today I had the time to test it again with the latest version of
> OpenELEC:
>
> All frequenzies but 25 Hz are working. With 25 Hz I still get the known
> up/down-flickering effect :(
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/2924#issuecomment-98397293>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by chewitt** [comment] 2015-08-20 11:57
closing as the issue is reported and can be tracked upstream

**Closed by chewitt** 2015-08-20 11:57 UTC
