### ISSUE TITLE
Wired ethernet and wifi at same time produces wrong routing table.

### ISSUE THREAD

**Issue by trevorjharris** [OpenELEC/OpenELEC.tv#4584] opened 2016-01-07 11:02 UTC
Have Raspberry pi 2 running Kodi 17 release 106. I have configured both wired and wifi internet.

OpenELEC:~ # ifconfig
eth0      Link encap:Ethernet  HWaddr B8:27:EB:6E:5E:43
          inet addr:192.168.124.1  Bcast:192.168.124.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:198 errors:0 dropped:0 overruns:0 frame:0
          TX packets:843 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:48662 (47.5 KiB)  TX bytes:151761 (148.2 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:94 errors:0 dropped:0 overruns:0 frame:0
          TX packets:94 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:8300 (8.1 KiB)  TX bytes:8300 (8.1 KiB)

wlan0     Link encap:Ethernet  HWaddr FC:B4:E6:AA:52:52
          inet addr:192.168.123.125  Bcast:192.168.123.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:693941 errors:0 dropped:130025 overruns:0 frame:0
          TX packets:262122 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:199982073 (190.7 MiB)  TX bytes:27052744 (25.7 MiB)

OpenELEC:~ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.123.254 0.0.0.0         UG    0      0        0 eth0
192.168.123.0   *               255.255.255.0   U     0      0        0 wlan0
192.168.123.254 *               255.255.255.255 UH    0      0        0 eth0
192.168.123.254 *               255.255.255.255 UH    0      0        0 wlan0
192.168.124.0   *               255.255.255.0   U     0      0        0 eth0

As you see the default route uses the wired interface eth0 but should be using wlan0. Also there are 2 routes to 192.168.123.254 when there should not be one using eth0. 

Please can this be fixed.

**Comment by stefansaraev** [comment] 2016-01-07 16:41
this is not a bug. when connected, ethernet is always preferred. so this is intended behaviour.

https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/network/connman/package.mk#L92

**Comment by trevorjharris** [comment] 2016-01-07 17:35
Ok prehaps not a bug but a poor design. There should be a way of configuring an interface that is not a default route. By changing the preferedtechnologies to put wifi first I was able to get it to work.

**Comment by chewitt** [comment] 2016-01-07 23:28
^^ based on that I am closing the ticket. Thanks.

**Closed by chewitt** 2016-01-07 23:28 UTC
