### ISSUE TITLE
curl/thumbnails problems via FTP in openELEC 5.0.1

### ISSUE THREAD

**Issue by delinend** [OpenELEC/OpenELEC.tv#3866] opened 2015-02-04 06:34 UTC
Hi.

After update of the curl in openELEC 5.0.1, the Thumbnails download via FTP is not working anymore.
Here the advancedsettings.xml:
```
<?xml version="1.0" encoding="UTF-8" ?> 
 <advancedsettings>
   <ftp>
     <remotethumbs>true</remotethumbs> 
   </ftp>
 </advancedsettings>
```

It look like the problem came into openELEC when going from curl 7.38.0/7.39.0 to version 7.40.0 !!!
Here my kodi.log file, from last openELEC 5.0.1 official build: http://pastebin.com/22K5hhkJ

Can anyone help ?

Thanks and best regards.

**Comment by stefansaraev** [comment] 2015-02-04 09:42
@sraue that's exactly what I am talking about...

**Comment by fritsch** [comment] 2015-02-04 09:46
https://github.com/OpenELEC/OpenELEC.tv/commit/eb4cdd818609c24c2d06b5c7cdef35f2cfd2b5c9 @delinend can you revert this one and retry?

**Comment by delinend** [comment] 2015-02-04 10:12
@fritsch Sorry. I don't know how to do that.
I have last night made some testing with Milhouse, and there we was seeing the problem came, when going from curl 7.39.0 to 7.40.0: http://forum.kodi.tv/showthread.php?tid=211501&pid=1913864#pid1913864
Is ther a easy way, where I can test your revert ?

**Comment by MilhouseVH** [comment] 2015-02-04 10:39
@fritsch: It appears the problem is there in curl 7.39.0 in OpenELEC (but, oddly, not in curl 7.39.1 on Windows). There is no problem with curl 7.37.1 in OpenELEC.

@delinend: I can create a test build reverting 7.40.0 to 7.39.0, so that you can re-test this.

**Comment by stefansaraev** [comment] 2015-02-04 10:42
@MilhouseVH just when reverting curl, also rebuild everything that uses curl. including kodi. thanks.

**Comment by delinend** [comment] 2015-02-04 10:44
@MilhouseVH: Many thanks. I'm ready to test, when you got it build.

**Comment by fritsch** [comment] 2015-02-04 10:49
We had a manual patch for 7.0.39, cause  there was an upstream issue - make sure to add that patch again, please.

**Comment by MilhouseVH** [comment] 2015-02-04 10:58
Do you know offhand which patch that was?

**Comment by delinend** [comment] 2015-02-04 11:10
@MilhouseVH: @fritsch wrote http://sourceforge.net/p/curl/bugs/1426/

**Comment by stefansaraev** [comment] 2015-02-04 11:13
you dont need that patch. just revert to 1.39.0

**Comment by MilhouseVH** [comment] 2015-02-04 11:17
Uploading now, have rebuilt curl + kodi + kodi-pvr-addons...

**Comment by MilhouseVH** [comment] 2015-02-04 11:24
@delinend, try this curl 7.39.0 build: http://milhouse.openelec.tv/builds/testing/RPi/OpenELEC-RPi.arm-Milhouse-20150204104821-r20200-g92ada94.tar

**Comment by delinend** [comment] 2015-02-04 11:35
@MilhouseVH: Just updates openELEC 5.0.1 with your build #204b and it' NOT working. Same problem :-(
Here my log: http://pastebin.com/4TmQF1B3

**Comment by MilhouseVH** [comment] 2015-02-04 11:37
OK, that's what I expected, as you've already said curl 7.37.1 is the last known working version.

**Comment by MilhouseVH** [comment] 2015-02-04 11:51
I'll upload another test build, this time with curl 7.37.1. Then someone can decide on what to do... :)

**Comment by fritsch** [comment] 2015-02-04 11:51
Care to provide a build with 7.37.1 (and the referenced patch), please?

2015-02-04 12:37 GMT+01:00 MilhouseVH <notifications@github.com>:

> OK, that's what I expected, as you've already said curl 7.37.1 is the last
> known working version.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3866#issuecomment-72840616>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by MilhouseVH** [comment] 2015-02-04 11:53
This is the patch I'm using for the next test build.

http://sprunge.us/gTdB

**Comment by fritsch** [comment] 2015-02-04 11:54
Never mind - .37.1 is fine ...

**Comment by MilhouseVH** [comment] 2015-02-04 12:21
@delinend, curl 7.37.1 build here: http://milhouse.openelec.tv/builds/testing/RPi/OpenELEC-RPi.arm-Milhouse-20150204114948-r20200-g92ada94.tar

**Comment by delinend** [comment] 2015-02-04 12:28
@MilhouseVH: We are fast now...
Yes, the last build #204c is working fine now.
```
OpenELEC:~ # curl -V
curl 7.37.1 (armv6zk-openelec-linux-gnueabi) libcurl/7.37.1 OpenSSL/2.0.0 zlib/1.2.8 librtmp/2.3
Protocols: file ftp ftps gopher http https rtmp rtsp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz
OpenELEC:~ #
```
Where are we going from here ?

**Comment by MilhouseVH** [comment] 2015-02-04 12:34
You said (on the forum) that the current Kodi on Windows is working fine, which would mean the version used by Kodi, curl 7.39.1, is fine. However in OpenELEC, 7.39.0 is not fine. This, is odd. Are you 100% certain that Kodi on Windows (a recent master) is fine?

**Comment by delinend** [comment] 2015-02-04 12:48
I have just installed and testet new Kodi x86 (15.0-ALPHA1 Git:20150203-1fd79f4) version, on my laptop, and it works fine. How do I see the curl version, on a Windows setup ?
Here my new log: http://pastebin.com/9YHh2zzN

**Comment by delinend** [comment] 2015-02-04 12:58
Hmmm. I found a libcurl.dll in my c:\Programmer (x86)\Kodi\system\
If I right-click on that dll, and show's details, it say's:
```
libcurl.dll

libcurl Shared Library
7.21.6
Change date 24-04-2011
```
Very old :-(

**Comment by delinend** [comment] 2015-02-04 13:11
I have just made a verifikation on my Windows installation...
Uninstalled Kodi, and removed the Kodi folder.
Made a new installation of Kodi x86 (15.0-ALPHA1 Git:20150203-1fd79f4).
And the libcurl.dll is still version 7.21.6
Installed Kodi from Nightly here: http://mirrors.kodi.tv/nightlies/win32/

**Comment by stefansaraev** [comment] 2015-02-04 13:44
ubuntu (14.10 here) uses 7.37.1

kodi uses in uni deps:
- 7.21.6 on windows
- 7.39.0 on others that use unified deps.
@wsnipex is 7.39.0 also broken on android/rbpi/osx builds ?

@sraue I suggest downgrading to last working version (7.37.1), that is also used by ubuntu, and stick with what ubuntu uses. every curl bump in last one year broke something ;(

**Comment by wsnipex** [comment] 2015-02-04 14:08
I'm not aware of any curl issues on any kodi platform, but if this issue is limited to ftp, its possible.
I'd like to see a debug log with curl extra logging.

**Comment by delinend** [comment] 2015-02-04 14:29
@wsnipex: When I use FTP.. everything works fine. Directory browsing, and stating playback of movies. But fails only when retriving tbn (Thumbnails) via FTP. Kodi show only the default movie-strip icon, on all movies.
I remember log time ago, that there also was a resume problem, but I hav not tested that. How do we set extra curl logging ?

**Comment by wsnipex** [comment] 2015-02-04 15:28
in settings, right under the option to enable debugging. settings - system - debugging - Enable component specific logging - specify component specific logging

**Comment by delinend** [comment] 2015-02-04 16:07
@wsnipex: Here Specific curl logging, from my official openELEC 5.0.1 installation: http://pastebin.com/Q9eLPyXQ

**Comment by wsnipex** [comment] 2015-02-04 17:42
thanks. Can anyone make a build with http://paste.ubuntu.com/10057078/ ? would be interested if that helps.

**Comment by wsnipex** [comment] 2015-02-04 17:52
@delinend do you have a log with curl extra logging where it works? From an older OE version or windows?

**Comment by delinend** [comment] 2015-02-04 18:03
@wsnipex: Yes... Here is the log: http://pastebin.com/45TywuJJ
```
OpenELEC:~ # curl -V
curl 7.37.1 (armv6zk-openelec-linux-gnueabi) libcurl/7.37.1 OpenSSL/2.0.0 zlib/1.2.8 librtmp/2.3
Protocols: file ftp ftps gopher http https rtmp rtsp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz
OpenELEC:~ #
```

**Comment by wsnipex** [comment] 2015-02-04 19:40
thank you, exactly what I expected. I think this is a kodi bug thats exposes now because curl proably changed the curl return code for CURLINFO_CONTENT_LENGTH_DOWNLOAD. In that case, the patch from above would help, although its not the correct fix.

**Comment by delinend** [comment] 2015-02-04 19:55
@MilhouseVH: Can you help again, to make a test build, with this Patch from @wsnipex ?
http://paste.ubuntu.com/10057078/

**Comment by MilhouseVH** [comment] 2015-02-04 21:41
Sorry, been away from computers for a bit... Sure, I'll upload a build with
that patch in the next hour. Tonight's builds are currently uploading,
they're based on 7.37.1.

**Comment by MilhouseVH** [comment] 2015-02-04 23:29
@delinend New curl 7.40.0 build with @wsnipex patch: http://milhouse.openelec.tv/builds/testing/RPi/OpenELEC-RPi.arm-Milhouse-20150204224624-r20202-gdc87b24.tar

**Comment by delinend** [comment] 2015-02-05 05:45
@MilhouseVH: The r20202 version, with curl 7.40.0 and the patch from @wsnipex works fine :-)
What do we do from here ?
```
OpenELEC:~ # curl -V
curl 7.40.0 (armv6zk-openelec-linux-gnueabi) libcurl/7.40.0 LibreSSL/2.0.0 zlib/1.2.8 librtmp/2.3
Protocols: file ftp ftps gopher http https rtmp rtsp smb smbs
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
OpenELEC:~ #
```

**Comment by MilhouseVH** [comment] 2015-02-05 06:21
Up to OpenELEC really. Being so far ahead of Kodi in terms of curl version is causing the problem here. Maybe it's time for Kodi to update, in which case there's no need to carry the patch from @wsnipex in OpenELEC. Otherwise OpenELEC stick with 7.40.0 but carry this extra Kodi patch, or revert to 7.37.1 and forget about upgrading curl ever again until Kodi does the same.

**Comment by fritsch** [comment] 2015-02-05 07:22
+1 to all the solutions @MilhouseVH said.

2015-02-05 7:21 GMT+01:00 MilhouseVH <notifications@github.com>:

> Up to OpenELEC really. Being so far ahead of Kodi in terms of curl version
> is causing the problem here. Maybe it's time for Kodi to update, in which
> case there's no need to carry the patch from @wsnipex
> <https://github.com/wsnipex> in OpenELEC. Otherwise OpenELEC stick with
> 7.40.0 but carry this extra Kodi patch, or revert to 7.37.1 and forget
> about upgrading curl ever again until Kodi does the same.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3866#issuecomment-73000205>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by wsnipex** [comment] 2015-02-05 08:06
Imho this has to be fixed properly in kodi. There is something wrong with the curl callback functions and how we handle potentially unknown file sizes. I'll try to look into it. If you decide to go with this patch in the meantime, we'd at least know if there is any fallout on other protocols then ftp :)

**Comment by wsnipex** [comment] 2015-02-08 13:24
can you test https://github.com/wsnipex/xbmc/commit/84ee922e4090c155cd5ed5e17973bcbb27a95d2f instead of the earlier patch?

**Comment by delinend** [comment] 2015-02-08 16:57
@MilhouseVH: Can you help again, to make a new test build, with @wsnipex new fix ?

**Comment by MilhouseVH** [comment] 2015-02-09 01:45
I've uploaded a curl 7.40 + https://github.com/wsnipex/xbmc/commit/3eec72d4fd109e9f153a375138c1a997bcf86d9a test build for RPi here:

http://milhouse.openelec.tv/builds/testing/RPi/OpenELEC-RPi.arm-Milhouse-20150209012026-r20236-g2ca87fa.tar

**Comment by delinend** [comment] 2015-02-09 07:35
@wsnipex and @MilhouseVH: I have just tested the #0209 build with the wsnipex/xbmc@ 3eec72d + curl 7.40 and it works fine here by me now :-)

**Comment by wsnipex** [comment] 2015-02-09 08:37
@MilhouseVH thanks for the build
@delinend thanks for testing, could you post another log with curl extra logging?

**Comment by delinend** [comment] 2015-02-09 09:55
@wsnipex Her a new log: http://pastebin.com/hhbA0dFA
Thanks for your help.

**Comment by stefansaraev** [comment] 2015-02-11 18:01
closing as fixed

**Closed by stefansaraev** 2015-02-11 18:01 UTC
Labels: Bug, confirmed
