### ISSUE TITLE
TV keeps waking up over HDMI-CEC connected RPi/RPi2

### ISSUE THREAD

**Issue by gpomykala** [OpenELEC/OpenELEC.tv#4086] opened 2015-04-08 20:11 UTC
It seems to be a long standing issue - i've had the issue in OpenElec 4.x on RPi Model B, same with 5.x on RPi2.

All revelant wake up / stand by related settings are disabled in Kodi settings, the only thing I need CEC for is to use TV remote to control Kodi.
TV keeps waking up when left overnight. RPi does not support sleep hence it's turned on all the time on kodi main menu screen.

**Comment by 3ddd** [comment] 2015-04-18 15:36
Same here with OE 5.0.8 and RPI 1 B.
Why it is invalid marked? Cause of the missing Logs?

**Comment by popcornmix** [comment] 2015-04-18 18:08
Read https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md
The forum is generally the right place for questions like this.

**Comment by 3ddd** [comment] 2015-04-18 20:46
Same Problems also here: http://openelec.tv/forum/124-raspberry-pi/76334-rpi2-turn-on-my-tv

**Comment by stefansaraev** [comment] 2015-04-18 20:48
hey @3ddd, thank you very much for your "+1 me too"! very helpful

logs/details or I close this in 24 hours.

**Comment by 3ddd** [comment] 2015-04-18 20:54
Hey Stefan, sorry the Issue don't happen every night and it's on the RPI from my parents, so i'm not able to provide logs so fast. Only wanted to say that this isn't an solitary case here.

**Comment by gpomykala** [comment] 2015-04-18 20:57
I can gather some logs if I only knew how to configure it properly

**Comment by 3ddd** [comment] 2015-04-18 21:04
http://wiki.openelec.tv/index.php?title=OpenELEC_FAQ#How_do_I_generate_support_logs.3F

**Comment by gpomykala** [comment] 2015-04-18 21:14
Hi,
Here's the log of my system -> http://1drv.ms/1yEP1Aq

It did turn the TV on last night sometime between 2AM and 8AM GMT.


2015-04-18 22:04 GMT+01:00 DDD <notifications@github.com>:

**Comment by yonatanp** [comment] 2015-05-09 10:46
Happens on my setup as well. Wakes up the TV randomly around 2 hours after I turn it off. Confirmed to happen in various cases, such as when video is playing, or paused, or nothing playing at all, or after pi has been restarted. If I can help with the process - I'd be happy to, just tell me how.

**Comment by andrelung** [comment] 2015-06-02 10:16
I am having the same problem, but I am also struggeling with the basics. Does anyone around here know, how to prevent kodi from waking up the tv, when a simple notification pops up (but maintain waking up, when I press some keys on my kodi remote)

Thanks!

**Comment by utdrmac** [comment] 2015-10-01 05:56
Even with CEC disabled, pi still turns TV back on. Usually after only 2 minutes.

**Comment by 3ddd** [comment] 2015-10-01 06:40
Have you tried latest 6.0 OE Beta?

**Comment by utdrmac** [comment] 2015-10-13 16:36
Here's my log: http://sprunge.us/DBbQ
I've tried many different options and OpenELEC continues to turn my TV back on after I turn it off. You can see in the logs the TV "power status changed from 'on' to 'standby'". Then a minute later, Cec does some broadcasting which causes the TV and audio receiver to turn back on. But if you just have the TV on, Cec does NOT do this broadcasting stuff. It's as if the action of turning the TV off triggers this broadcasting.

CEC Adapter. ProductID 1001 Venrod: 2708. Version libCEC 2.2.0.

Devices to power on when starting kodi: None
Devices to power off when stopping kodi: None
When the TV is switched off: Suspend  (<-- this never happens either. I was expecting Kodi to sleep when I turn the TV off)

My pi is plugged in to my receiver's input 1 and the TV plugged in to receiver output.

If there is a better place to submit this bug, let me know. Happy to help.

**Comment by lrusak** [comment] 2015-10-13 17:22
@utdrmac Do you use cec at all? can you try disabling it in the config.txt?

see, http://wiki.openelec.tv/index.php/Config.txt
and use ```hdmi_ignore_cec=1```

reference, http://elinux.org/RPiconfig

**Comment by utdrmac** [comment] 2015-10-13 17:50
I would like to continue using CEC because the left, up, down, play, pause, etc buttons on my TV remote work well with OpenELEC. This is new behavior, the TV coming back on. So, not sure where the bug is. I don't recall updating any libraries or anything like that. This behavior with libcec only seems to happen when the TV is turned off.

**Comment by popcornmix** [comment] 2015-10-15 17:15
@utdrmac Any other CEC capable devices connected to TV/receiver?
Might be worth disconnecting other devices and see if it is some incompatibility.

**Comment by schumi2004** [comment] 2015-10-15 18:11
Having the same issue but it happens randomly.
I noticed it a few times because the whole bedroom became lit and it waked me up.
Funny thing is that when it happend it completly ignored the CEC settings to turn of TV when screensaver kicks in.

**Comment by jackiass** [comment] 2015-10-23 06:45
I've had this problem for years now. Also with the RPi1. It's very frustrating. Whenever I turn off the tv, I have to do it 2-4 times before it stays turned off. I have as of yet not found a solution other than disabling CEC all together, which is not really a solution.

**Comment by mandriospo** [comment] 2015-11-11 11:20
I have exactly same problem as described. RPi turns my Samsung TV randomly. Few times it wakes my little son at night or when he sleep during the day. Very frustrating!

**Comment by utdrmac** [comment] 2015-11-11 15:00
I'd love to help diagnose this if someone (a dev) could tell me what he/she needs me to provide.

**Comment by chewitt** [comment] 2016-02-08 06:42
I'm closing this ticket due to age and lack of update. OE 6.0.1 contains updated libCEC so please update and if there are further CEC issues report them via a thread in the forums. Thanks.

**Closed by chewitt** 2016-02-08 06:42 UTC
Labels: invalid

**Comment by cebess** [comment] 2018-02-15 20:34
Settings for your CEC devices can be found in:

System -> Settings -> System -> Input Devices -> Peripherals -> CEC adapter

I had to play with some of the settings about startup and shutdown of Kodi until I figured out what worked.
