### ISSUE TITLE
Video lags appear in 1080P files after upgrade to 5.95.5

### ISSUE THREAD

**Issue by ofir38** [OpenELEC/OpenELEC.tv#4339] opened 2015-09-24 17:12 UTC
1. Working with HTPC Arctic MC001
2. Current vesrion - 5.0.8
3. Run 1080P files -> Files run smoothly without problem
4. Upgrade to OE 5.95.5 
5. Run 1080P files -> Most of the filses have a lot of lags. Video does not play smoothly.
6. The case was reproduced at Sep 24 , 12:50 & 13:19

See Kodi log here - http://goo.gl/dDMx7Z

**Comment by fritsch** [comment] 2015-09-24 17:19
Please reproduce without illegal addons from a local file.

If you don't have one - here is one:
https://dl.dropboxusercontent.com/u/55728161/clannad.mkv

Also remove your 1000 channels iptv which you probably also watch not legal.

OE Team won't support piracy video streams.

2015-09-24 19:12 GMT+02:00 ofir38 <notifications@github.com>:

>
>    1. Working with HTPC Arctic MC001
>    2. Current vesrion - 5.0.8
>    3. Run 1080P files -> Files run smoothly without problem
>    4. Upgrade to OE 5.95.5
>    5. Run 1080P files -> Most of the filses have a lot of lags. Video
>    does not play smoothly.
>    6. The case was reproduced at Sep 24 , 12:50 & 13:19
>
> See Kodi log here - http://goo.gl/dDMx7Z
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4339>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by ofir38** [comment] 2015-09-24 17:24
You mean to reproduce with the attached mkv you provided ?

**Comment by fritsch** [comment] 2015-09-24 17:37
I want to see a clean log without any piracy addons and then you playing the above sample.

**Comment by ofir38** [comment] 2015-09-24 18:10
Is it ok to disable all unnecessary addons ?

**Comment by ofir38** [comment] 2015-09-24 18:13
PLease take a look here - http://goo.gl/YYJtDQ

**Comment by fritsch** [comment] 2015-09-24 18:15
The log is still full of those addons, one cannot see a single thing, sorry
...

2015-09-24 20:13 GMT+02:00 ofir38 <notifications@github.com>:

> PLease take a look here - http://goo.gl/YYJtDQ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4339#issuecomment-143008617>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by ofir38** [comment] 2015-09-24 18:22
OK. 
I will clean everything. It will take few minutes

**Comment by ofir38** [comment] 2015-09-24 19:38
OK... I have it...
Net log without addons....
http://goo.gl/z89d78

**Comment by fritsch** [comment] 2015-09-24 19:41
All fine.

What's the issue?

2015-09-24 21:38 GMT+02:00 ofir38 <notifications@github.com>:

> OK... I have it...
> Net log without addons....
> http://goo.gl/z89d78
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4339#issuecomment-143028592>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by ofir38** [comment] 2015-09-24 19:43
In the sample you gave me i did not see the problem.
before there were a lot of lags while playing 1080P files

**Comment by fritsch** [comment] 2015-09-24 20:24
Then show me a sample that produces the issues and post another debuglog.

2015-09-24 21:44 GMT+02:00 ofir38 <notifications@github.com>:

> In the sample you gave me i did not see the problem.
> before there were a lot of lags while playing 1080P files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4339#issuecomment-143029940>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by chewitt** [comment] 2015-12-27 06:18
I'm closing this due to lack of specific evidence. If you still see issues please wait for 6.0.1 before opening a forum thread (this is not a user-help forum) or perhaps try a milhouse Jarvis build. Thanks.

**Closed by chewitt** 2015-12-27 06:18 UTC
