### ISSUE TITLE
Manual IP4 settings not saving in 5.0.8 RPi2 

### ISSUE THREAD

**Issue by ngodber** [OpenELEC/OpenELEC.tv#4081] opened 2015-04-07 12:15 UTC
Tried to configure IPv4 settings to manual (using network switch) for eth0, system allows user to edit, select manual and enter IP and Subnet however on selecting either 'save' or 'connect' prompt closes and the settings are not retained (type remains 'dhcp' and not changes can be seen). Have tried saving and immediately restarting, without success.

I believe the system should save the manual settings and show type 'manual' on 'Connections' screen with the specified address displayed.

**Comment by ngodber** [comment] 2015-04-07 12:49
apologise, logged in openelec.settings

**Comment by stefansaraev** [comment] 2015-04-07 14:19
no, it belongs here, was marked as invalid because no logs attached. 

you say you cant attach logs, but that doesnt make it easier for us

however, I'll try to reproduce your bug tonight (I dont have rpi hardware, so if it's real bug, I hope it's not rpi specific)

**Comment by ngodber** [comment] 2015-04-07 14:21
Gents, 

Managed to get logs out thanks to help of hans_s and others. Please see at https://drive.google.com/file/d/0B80PFF3u-fmoMmVackFPTXJiTDQ/view

**Comment by ngodber** [comment] 2015-04-07 14:26
And again after immediately recreating the issue

https://drive.google.com/file/d/0B80PFF3u-fmoQWdUaHk1c2MxZ1E/view?usp=sharing

**Comment by stefansaraev** [comment] 2015-04-07 14:27
gotcha. I see why. hope I can reproduce.

could you please enable debugging and catch new (debug) logs ? you can add "debugging" to cmdline.txt or "touch /storage/.cache/debug.openelec" via ssh

try reproduce again with logging enabled, and share the new logs. thanks.

**Comment by ngodber** [comment] 2015-04-07 14:38
ok please see latest, let me know if this worked 

https://drive.google.com/file/d/0B80PFF3u-fmoVWtpWjE4dkc2OFk/view?usp=sharing

**Comment by ngodber** [comment] 2015-04-07 14:43
I flashed back to 5.0.6 before opening ticket and the outcome was the same

**Comment by stefansaraev** [comment] 2015-04-07 16:45
good thing is that I can reproduce your bug when my dhcp server is down. I'll fix asap.

**Comment by stefansaraev** [comment] 2015-04-07 18:13
fixed in f6218f10ffdbfab9555cd8fb565a4ec99dd755d2 24ada74a87cda1be90b63e47f91d4f49341ea23a

I can't build for RPi2 atm, would be nice if anyone can do testbuild based on 5.0 branch for @ngodber

//cc @sraue @fritsch

**Comment by fritsch** [comment] 2015-04-07 18:20
The linked patches look the same?

**Comment by stefansaraev** [comment] 2015-04-07 18:21
sure they are, one for master and one for 5.0 :)

**Comment by fritsch** [comment] 2015-04-07 18:24
:-) that was too obvious.

2015-04-07 20:21 GMT+02:00 Stefan Saraev <notifications@github.com>:

> sure they are, one for master and one for 5.0 :)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4081#issuecomment-90688707>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by ngodber** [comment] 2015-04-07 22:53
All, back on deck. Happy to run a test build on RPi2 if it is available?

**Comment by ngodber** [comment] 2015-04-09 06:11
Has a test build been rolled per chance?

**Comment by ngodber** [comment] 2015-04-15 08:03
Gents, 

Tested on latest milhouse builds and own build of source and still encountering the issue, unchanged. Please see debug logs at https://drive.google.com/file/d/0B80PFF3u-fmobDFiZThOclFSTm8/view?usp=sharing

**Comment by ngodber** [comment] 2015-04-16 08:34
Ok, whilst the bug is still live, it is possible to set the network settings via ssh using connmanctl. So there is a viable workaround.

**Comment by stefansaraev** [comment] 2015-04-16 08:44
your "old" (crash) bug is fixed. the new one is something different, that I can not reproduce.

**Comment by ngodber** [comment] 2015-04-16 08:49
Is there anyway that using upgrade instead of a fresh image could have some effect?

**Comment by stefansaraev** [comment] 2015-04-16 09:28
probably, especialy if you are upgrading from a build before 5.0.2. wipe your /storage/.cache/connman and re-test.

**Comment by ngodber** [comment] 2015-04-16 13:51
Ok found what was doing wrong. Had to specify a dummy gateway then the settings were committed. Cheers for the support. This can be confirmed fixed.

**Comment by stefansaraev** [comment] 2015-04-16 13:54
> Had to specify a dummy gateway then the settings were committed. Cheers for the support. This can be confirmed fixed

correct. it's a bit confusng, I know. in future I'll make it so users get a notification when not all required fields are filled in.

thanks for confirming.

**Closed by stefansaraev** 2015-04-16 13:54 UTC
Labels: Bug, confirmed, Fix committed
