### ISSUE TITLE
VSYNC - some modes causes temporary freezes

### ISSUE THREAD

**Issue by JimmyS83** [OpenELEC/OpenELEC.tv#4446] opened 2015-11-18 05:48 UTC
Hi,
Since 6.0 (on Rpi2) I am experiencing freezing troubles, using mode VSYNC only on playback. Here is observations: http://openelec.tv/forum/90-miscellaneous/78754-frequent-hang-on-oe-6-0-chromebox-flirc#151974

Summary: When operating with OSD/GUI while video is playing, sometimes openelec generates freeze of GUI for 15-50 seconds. Sometimes OSD parts keep showing (like playbar, when I already play video). Sometimes not (hard to regenerate), but it is quite often (if you want to watch two movies in evening, you certainly got a few of them. 

From log I dig only this:
CDVDMsgGeneralSynchronize - global timeout message, and after restoration of OSD is Thread JobWorker xxx terminating (autodelete)

The problem completelly dissapear when VSYNC Always ON is turned on. And it wasnt present on previous stable, 5.0.8.

Regarding forum post, I think this is not only RPi2 arch observation.

**Comment by popcornmix** [comment] 2015-11-21 14:48
I'm sure the issue you have is unrelated to the Chromebox issue.
On Pi2 VSYNC defaults to "Always enabled".
If changing a setting sway from its default makes the behaviour worse, then I'd suggest leaving it at the default.

**Comment by JimmyS83** [comment] 2015-11-23 11:10
Yes, I am using mode without bug, but still, if there are other modes avaible, it would be good if someone can look, what happen and what can cause this (other modes works very well in 5.0.8).

Previously I used VSYNC only with video (which now I cant), and since I have this setting changed before update to 6.0, it takes me a while, until I found root cause..

**Comment by chewitt** [comment] 2016-02-08 06:50
I'm closing this ticket because the default RPi2 config is working as intended (and due to lack of further update). Thanks.

**Closed by chewitt** 2016-02-08 06:50 UTC
