### ISSUE TITLE
Cubox-i4pro, OpenELEC 5.0.2: Internal SDIO bluetooth not detected

### ISSUE THREAD

**Issue by GammaC0de** [OpenELEC/OpenELEC.tv#3926] opened 2015-02-19 23:49 UTC
Hi,
I have a Cubox-i4pro.
I'm tring to use the internal SDIO bluetooth with OpenELEC since version 5 RC1 but OpenELEC does not detect a bluetooth device.

```
Openelec:/ # hcitool dev
Devices:
Openelec:/ #
```
dmesg output: http://pastebin.com/RwjrJi29

**Comment by piso77** [comment] 2015-03-04 12:33
well, actually the brcmfmac service is stuck at boot:

OpenELEC:~ # systemctl status brcmfmac_sdio-firmware@bcm4330.service
● brcmfmac_sdio-firmware@bcm4330.service - Broadcom sdio firmware update for bcm4330
   Loaded: loaded (/usr/lib/systemd/system/brcmfmac_sdio-firmware@.service; static)
   Active: activating (start) since Thu 1970-01-01 01:23:02 UTC; 1min 1s ago
 Main PID: 776 (brcm_patchram_p)
   CGroup: /system.slice/system-brcmfmac_sdio\x2dfirmware.slice/brcmfmac_sdio-firmware@bcm4330.service
           └─776 /usr/bin/brcm_patchram_plus --patchram /lib/firmware/brcm/bcm4330.hcd --baudrate 3000000 --use_baudrate_for_download /d...


and if you turn on the serial console during boot (add "console=ttymxc0,115200" to uEnv.txt), you'll notice that the service hangs there forever:

...
[  OK  ] Reached target Network.
         Starting Avahi Daemon...
[  OK  ] Started Avahi Daemon.
         Starting RPC bind service...
         Starting OpenSSH server daemon...
[  OK  ] Created slice system-lircd.slice.
         Starting Lirc with lirc0:default:lircd.conf...
[  OK  ] Created slice system-brcmfmac_sdio\x2dfirmware.slice.
         Starting Broadcom sdio firmware update for bcm4330...
[  OK  ] Stopped Udevil mount service.
[  OK  ] Stopped Udevil mount service.
[  OK  ] Created slice system-udevil\x2dmount.slice.
         Starting Udevil mount service...
         Starting Udevil mount service...
[  OK  ] Reached target Sound Card.
[  OK  ] Started RPC bind service.
[  OK  ] Started OpenSSH server daemon.
[  OK  ] Started Lirc with lirc0:default:lircd.conf.
[  OK  ] Started Udevil mount service.
[  OK  ] Started Udevil mount service.
         Starting WPA supplicant...
         Starting ConnMan VPN service...
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.
         Starting Kodi Media Center...
[  OK  ] Started Kodi Media Center.
[  OK  ] Started ConnMan VPN service.
[  OK  ] Reached target Kodi Mediacenter Interface.
[  OK  ] Reached target Bluetooth.
[  OK  ] Started WPA supplicant.
[   ***] A start job is running for Broadcom...ate for bcm4330 (7min 8s / no limit)

On ssh, after stopping that service, i tried to start it manually (adding the debug flag -d):

OpenELEC:~ # systemctl stop brcmfmac_sdio-firmware@bcm4330.service
...
OpenELEC:~ # grep patchram /usr/lib/systemd/system/brcmfmac_sdio-firmware@.service 
ExecStart=/usr/bin/brcm_patchram_plus --patchram /lib/firmware/brcm/%I.hcd --baudrate 3000000 --use_baudrate_for_download /dev/ttymxc3 --enable_hci --no2bytes --tosleep=50000
...
OpenELEC:~ # /usr/bin/brcm_patchram_plus --patchram /lib/firmware/brcm/bcm4330.hcd --baudrate 3000000 --use_baudrate_for_download /dev/ttymxc3 --enable_hci --no2bytes --tosleep=50000 -d
/dev/ttymxc3 
writing
01 03 0c 00 
writing
01 03 0c 00 
writing
01 03 0c 00 
writing
01 03 0c 00 
writing
01 03 0c 00 
writing
01 03 0c 00 
writing
01 03 0c 00 
writing
01 03 0c 00 
...

and we get no answer form the hardware.

So, to further debug this i need to know:

1) where is the src code (and config) for the kernel used on this img?

OpenELEC:~ # uname -a
Linux OpenELEC 3.14.25 #1 SMP Sat Feb 28 08:53:52 CET 2015 armv7l GNU/Linux
OpenELEC:~ # cat /etc/release 
imx6.arm-5.0.5

actually cubox sponsor a 3.14.14 kernel so i'm really curious to see what's in this kernel.

2) where is the src code for brcm_patchram_plus, it might need some patching.

Hope someone can give me the info i need to further debug this, and please don't mark this as a feature request, since it's clearly a bug.

**Comment by chewitt** [comment] 2015-12-22 04:30
is this still an issue on OE 6.0.0?

**Comment by GammaC0de** [comment] 2015-12-22 08:54
@chewitt  Yes it is.

**Comment by vpeter4** [comment] 2015-12-25 10:39
The problem is that device hci0 must be bring up with command
```
/usr/bin/hciconfig hci0 up
```
After that hcitool see the device.

Will send PR with a fix for this.

**Closed** 2015-12-25 12:16 UTC
Labels: imx6

**Comment by oblitum** [comment] 2016-02-09 13:32
Hello Guys!

Can anyone give me a tip, not exact, of how long it will take for my home device to receive the version where a bluetooth headset starts to work? My Cubox-i in at 6.0.1.

I was trying to connect my bluetooth headset at home and ended up here. Device is found but I get an error about protocol not being supported.

**Comment by vpeter4** [comment] 2016-02-09 16:09
@oblitum: try https://drive.google.com/file/d/0B4FdVu0-fJt6ak1sWXh1a0phc0U/view?usp=sharing
It has some pulseaudio stuff in which supports BT devices like BT speaker.

**Comment by oblitum** [comment] 2016-02-10 01:43
Thanks @vpeter4, I just wanted a vague idea of timing, I'm not leaning towards applying a new developing kernel or anything. Thanks for the pointer though.

**Comment by chewitt** [comment] 2016-02-10 03:07
@sraue dictates when anything will be released and since he doesn't communicate with anyone else on the project in a meaningful way (aside from warning us we must not communicate any dates on releases) we honestly have no clue when a release will come. The build vpeter linked to should be quite stable. No harm in having a play with a spare SD card..

**Comment by oblitum** [comment] 2016-02-10 03:29
@chewitt ah indeed, sometimes I just forget it's as easy as trying on a new SD card.

**Comment by sraue** [comment] 2016-02-10 16:07
@chewitt, we never gave any ETAs except one time where we then had very very bad comments in forums etc because we had some problems to solve and missed this ETA.
As you maybe know its not only OpenELEC who dont gives ETAs, but many many other projects too. So i am not sure why you again bitch me personally because of this.

**Comment by chewitt** [comment] 2016-02-11 02:25
@sraue, I bitch because there is no date for 7.0 beta (not even a rough one) for project efforts to rally behind so the wider project team continue to tinker with their own thing of interest instead of objectively working towards a common target. You are the founder and self-proclaimed leader of this project but you are a leader who is not doing much leading. The project got too big for one person to do everything and your personal circumstances changed so you have less time to spend on things. Yet you refuse to share the general burden of running things with people who are capable and willing to do them. You do not communicate with people so even if you are doing something positive towards the unknown goals of the project we have negative visibility of it. As a good example: The forum Tapatalk install has been broken for months due to your paranoia of sharing admin rights/credentials with people who want to fix it (and know how). An increasing number of people see you as an obstruction to the project and its forward progress. I have personally defended you against these opinions for a long time, but I too am exhausted by your attitude. I don't care what the date for 7.0 beta is, but I care there is a date, a target. I care because if there continues to be no plan for this project the public shambles of OpenELEC 6.0 release will be repeated again (and again). I am bitching because I care.
